## Paths

In [43]:
intervals_path = "gs://fc-9b3068ac-c9f3-48c2-b157-5d7e7286e32f/twist_hg38_targets.interval_list"

paths_na12878 = ['gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/c5a89822-b126-4f64-a769-794a2db2d4d5/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/d8f9fe2b-a079-4fae-88e9-fa6fe8d0e06b/call-FilterVCF/0437225738.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/19908fa6-c22b-40da-84c7-be6a6c151da5/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/b08b14a1-90f7-45ed-81dd-88e6f99c6e80/call-FilterVCF/0437225744.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/2610faa2-d735-4f13-a0ef-1ab481faa762/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/1168faac-ae1e-45b2-8c92-8d40f66e1c7f/call-FilterVCF/0437227355.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/504ce16a-0001-4f21-ba1c-effea2b92d7d/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/14c267a3-a4b8-4031-9513-14ecec6cbbc1/call-FilterVCF/0437227356.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/37a3ce6e-5d9c-4963-ae05-6f44331d8902/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/5a7c0cdf-d0da-4839-ac89-deaa02e2e288/call-FilterVCF/0437227363.filtered.genotyped-segments.vcf.gz']

paths_na24385 = ['gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/491aa495-33c0-41a9-a7e5-bb564dede818/CNVCallingAndMergeForFabric/c6396060-71d2-465c-84b2-0c2c2b4809c3/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/9764b4cf-af73-4095-940e-3e482abe684b/call-FilterVCF/0437225751.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/a6305bbb-6e10-4439-89e3-7cabac97a4d9/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/68b32369-7fc9-4d09-9f84-ee0eb88f1780/call-FilterVCF/0437225752.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/a0121b59-1d7f-4622-be5a-0e34a927077a/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/244d1d8e-88d1-43f3-885f-76f4ba9fc1ab/call-FilterVCF/0437225753.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/abb9ed4e-8fcd-44cb-b196-e3ae16bc166a/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/6f8e7059-cfc3-4684-b88f-27c4c864d29b/call-FilterVCF/0437225754.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/491aa495-33c0-41a9-a7e5-bb564dede818/CNVCallingAndMergeForFabric/82f0ad40-3db5-4bb3-8f28-468655d8231b/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/8289dd66-d420-4559-8161-5756121c8776/call-FilterVCF/0437225755.filtered.genotyped-segments.vcf.gz']

## Truth generation

In [59]:
paths = paths_na24385

In [60]:
import pandas as pd
import numpy as np


def add_exon_idxs(df, exons):
        contigs = set(df.contig)
        for contig in contigs:
            df.loc[df.contig==contig,"start_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].end,
                                                                       df.loc[df.contig==contig].start,"left")
            df.loc[df.contig==contig,"end_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].start,
                                                                       df.loc[df.contig==contig].end,"right")
def get_exon_expanded_events(df, exons):
    add_exon_idxs(df, exons)
    df = df.loc[df.start_exon_idx != df.end_exon_idx].reset_index().astype({'start_exon_idx':int,'end_exon_idx':int})
    df_expanded = df.loc[df.index.repeat(df.end_exon_idx-df.start_exon_idx)]
    df_expanded['exon_idx'] = df_expanded.groupby(df_expanded.index).cumcount() + df_expanded.start_exon_idx
    df_expanded = df_expanded.set_index(df_expanded.contig + "_" + df_expanded.exon_idx.astype(str))
    df_expanded = df_expanded.join(exons[['start','end']], rsuffix='_exon')
    df_expanded['event_exon_start']=np.maximum(df_expanded.start, df_expanded.start_exon)
    df_expanded['event_exon_end']=np.minimum(df_expanded.end, df_expanded.end_exon)
    df_expanded = df_expanded.set_index(df_expanded.index + "_" + df_expanded.svtype)
    return df_expanded

def extract_end_from_info(info):
    infos = info.split(';')
    for i in infos:
        if i.startswith('END='):
            return i.replace('END=', '')    

def read_vcf_to_df(vcf_path):
    df = pd.read_csv(vcf_path, sep='\t',comment='#',
                         names=['contig','start','ID','REF','ALT','QUAL','FILTER','INFO','FORMAT','SAMPLE'], dtype={'start': int})
    
    df = df.query("ALT != '.' and FILTER=='PASS'").copy()
    df['end'] = df['INFO'].apply(extract_end_from_info).astype(int)
    df["svtype"] = df.ALT.str.replace("<","").str.replace(">","")
    return df[['contig', 'start', 'end', 'ALT', 'svtype', 'ID']]

def read_intervals_to_df(intervals_path):
    intervals = pd.read_csv(intervals_path, sep="\t", comment="@", names = ["contig","start","end","dummy1","dummy2"], dtype={'start': int, 'end': int})
    intervals['contig_idx'] = intervals.groupby('contig').cumcount()
    intervals = intervals.set_index(intervals.contig + "_" + intervals.contig_idx.astype(str))
    return intervals

intervals = read_intervals_to_df(intervals_path)

control_events = pd.concat([read_vcf_to_df(path) for path in paths], ignore_index=True)
control_events_expanded = get_exon_expanded_events(control_events, intervals)
control_events_expanded = control_events_expanded.rename(columns={'index': 'event_id'})

index_sample_counts = control_events_expanded.groupby(control_events_expanded.index).size()
passing_indices = index_sample_counts[index_sample_counts >= 4].index
filtered_control_events_expanded = control_events_expanded.loc[passing_indices]

filtered_grouped_control_events = filtered_control_events_expanded.groupby(['contig', 'exon_idx', 'svtype']).agg({'event_exon_start': 'max', 'event_exon_end': 'min'}).reset_index()

def group_and_aggregate_events(df):
    df = df.sort_values(by='exon_idx')
    df['group'] = (df['exon_idx'].diff().fillna(1) != 1).cumsum()

    aggregated = df.groupby('group').agg({
        'event_exon_start': 'min',
        'event_exon_end': 'max',
    }).reset_index(drop=True)

    return aggregated

aggregated_events = filtered_grouped_control_events.groupby(['contig', 'svtype'], group_keys=True) \
    .apply(group_and_aggregate_events, include_groups=False).reset_index().drop(columns=['level_2']) \
    .rename(columns={'event_exon_start': 'start', 'event_exon_end': 'end'})

aggregated_events = aggregated_events.sort_values(by=['contig', 'start'],
                                                    key=lambda x: x.astype(str).str.replace('chr', '').astype(int))

truth = aggregated_events

In [66]:
index_sample_counts.to_frame().query('index.str.startswith("chr19")')

                 0
chr19_10860_DUP  1
chr19_10861_DUP  1
chr19_10862_DUP  5
chr19_10863_DUP  5
chr19_10864_DUP  5
chr19_10865_DUP  5
chr19_10866_DUP  5
chr19_10867_DUP  5
chr19_10868_DUP  5
chr19_10869_DUP  5
chr19_10870_DUP  5
chr19_10871_DUP  5
chr19_10872_DUP  5
chr19_10873_DUP  3
chr19_10874_DUP  3
chr19_10875_DUP  3

In [63]:
control_events_expanded.query('contig == "chr19"')

,event_id,contig,start,end,ALT,svtype,ID,start_exon_idx,end_exon_idx,exon_idx,start_exon,end_exon,event_exon_start,event_exon_end
chr19_10860_DUP,4,chr19,54783386,54825178,<DUP>,DUP,CNV_chr19_54783386_54825178,10860,10876,10860,54783486,54783538,54783486,54783538
chr19_10861_DUP,4,chr19,54783386,54825178,<DUP>,DUP,CNV_chr19_54783386_54825178,10860,10876,10861,54783637,54783813,54783637,54783813
chr19_10862_DUP,4,chr19,54783386,54825178,<DUP>,DUP,CNV_chr19_54783386_54825178,10860,10876,10862,54803652,54803691,54803652,54803691
chr19_10863_DUP,4,chr19,54783386,54825178,<DUP>,DUP,CNV_chr19_54783386_54825178,10860,10876,10863,54803891,54803926,54803891,54803926
chr19_10864_DUP,4,chr19,54783386,54825178,<DUP>,DUP,CNV_chr19_54783386_54825178,10860,10876,10864,54804793,54805077,54804793,54805077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
chr19_10868_DUP,32,chr19,54803552,54818699,<DUP>,DUP,CNV_chr19_54803552_54818699,10862,10873,10868,54813690,54813742,54813690,54813742
chr19_10869_DUP,32,chr19,54803552,54818699,<DUP>,DUP,CNV_chr19_54803552_54818699,10862,10873,10869,54813842,54814111,54813842,54814111
chr19_10870_DUP,32,chr19,54803552,54818699,<DUP>,DUP,CNV_chr19_54803552_54818699,10862,10873,10870,54816501,54816534,54816501,54816534
chr19_10871_DUP,32,chr19,54803552,54818699,<DUP>,DUP,CNV_chr19_54803552_54818699,10862,10873,10871,54817534,54817569,54817534,54817569
chr19_10872_DUP,32,chr19,54803552,54818699,<DUP>,DUP,CNV_chr19_54803552_54818699,10862,10873,10872,54818315,54818599,54818315,54818599

In [47]:

truth_na24385 = generate_truth(intervals_path, paths_na24385)

truth_na12878 = generate_truth(intervals_path, paths_na12878)

## Eval

In [48]:
truth = truth_na24385
path = paths_na24385[2]

In [50]:

import pandas as pd
import numpy as np

def add_exon_idxs(df, exons):
        contigs = set(df.contig)
        for contig in contigs:
            df.loc[df.contig==contig,"start_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].end,
                                                                       df.loc[df.contig==contig].start,"left")
            df.loc[df.contig==contig,"end_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].start,
                                                                       df.loc[df.contig==contig].end,"right")
def get_exon_expanded_events(df, exons):
    add_exon_idxs(df, exons)
    df = df.loc[df.start_exon_idx != df.end_exon_idx].reset_index().astype({'start_exon_idx':int,'end_exon_idx':int})
    df_expanded = df.loc[df.index.repeat(df.end_exon_idx-df.start_exon_idx)]
    df_expanded['exon_idx'] = df_expanded.groupby(df_expanded.index).cumcount() + df_expanded.start_exon_idx
    df_expanded = df_expanded.set_index(df_expanded.contig + "_" + df_expanded.exon_idx.astype(str))
    df_expanded = df_expanded.join(exons[['start','end']], rsuffix='_exon')
    df_expanded['event_exon_start']=np.maximum(df_expanded.start, df_expanded.start_exon)
    df_expanded['event_exon_end']=np.minimum(df_expanded.end, df_expanded.end_exon)
    df_expanded = df_expanded.set_index(df_expanded.index + "_" + df_expanded.svtype)
    return df_expanded

def extract_end_from_info(info):
    infos = info.split(';')
    for i in infos:
        if i.startswith('END='):
            return i.replace('END=', '')    

def read_vcf_to_df(vcf_path):
    df = pd.read_csv(vcf_path, sep='\t',comment='#',
                         names=['contig','start','ID','REF','ALT','QUAL','FILTER','INFO','FORMAT','SAMPLE'], dtype={'start': int})
    
    df = df.query("ALT != '.' and FILTER=='PASS'").copy()
    df['end'] = df['INFO'].apply(extract_end_from_info).astype(int)
    df["svtype"] = df.ALT.str.replace("<","").str.replace(">","")
    return df[['contig', 'start', 'end', 'ALT', 'svtype', 'ID']]

def read_intervals_to_df(intervals_path):
    intervals = pd.read_csv(intervals_path, sep="\t", comment="@", names = ["contig","start","end","dummy1","dummy2"], dtype={'start': int, 'end': int})
    intervals['contig_idx'] = intervals.groupby('contig').cumcount()
    intervals = intervals.set_index(intervals.contig + "_" + intervals.contig_idx.astype(str))
    return intervals

def read_truth(truth_path):
    truth = pd.read_csv(truth_path, sep="\t")
    truth = truth.reset_index(names='event_index')
    return truth

#intervals = read_intervals_to_df('~{exon_intervals}')
intervals = read_intervals_to_df(intervals_path)
#truth = read_truth('~{control_sample_common_events}')
truth = truth.reset_index(names='event_index')
#eval_df = read_vcf_to_df('~{eval_control_sample}')
eval_df = read_vcf_to_df(path)
eval_df_expanded = get_exon_expanded_events(eval_df, intervals)

truth_expanded = get_exon_expanded_events(truth, intervals)

truth_with_eval = truth_expanded.merge(eval_df_expanded, how="outer", suffixes=("_truth", "_eval"), indicator=True, left_index=True, right_index=True)

truth_with_eval['overlap_start']=np.maximum(truth_with_eval.event_exon_start_truth, truth_with_eval.event_exon_start_eval)
truth_with_eval['overlap_end']=np.minimum(truth_with_eval.event_exon_end_truth, truth_with_eval.event_exon_end_eval)

truth_with_eval['overlap_length']=np.maximum(truth_with_eval.overlap_end - truth_with_eval.overlap_start,0).fillna(0)

truth_with_eval['truth_length']=truth_with_eval.event_exon_end_truth - truth_with_eval.event_exon_start_truth
truth_with_eval['eval_length']=np.maximum(truth_with_eval.event_exon_end_eval - truth_with_eval.event_exon_start_eval,0).fillna(0)

truth_length_dedup = truth_with_eval.drop_duplicates(subset=['event_index', 'exon_idx_truth']).truth_length.sum()
eval_length_dedup = truth_with_eval.drop_duplicates(subset=['ID', 'exon_idx_eval']).eval_length.sum()

# Sensitivity
sensitivity = truth_with_eval['overlap_length'].sum()/truth_length_dedup

# Precision
precision = truth_with_eval['overlap_length'].sum()/eval_length_dedup

# Expected events seen
def group_truth_events(df):
    overlap_length = df.overlap_length.sum()
    truth_length_dedup = df.drop_duplicates(subset=['exon_idx_truth']).truth_length.sum()
    return overlap_length / truth_length_dedup

truth_events_fraction_covered = truth_with_eval.groupby(['event_index']).apply(group_truth_events)
expected_events_seen = truth_events_fraction_covered.sum()

# Expected events not seen
expected_events_not_seen = len(truth) - expected_events_seen

# Unexpected events seen
event_ids_matching_truth = truth_with_eval.loc[truth_with_eval['_merge'] == 'both', 'ID'].unique()
eval_only_events = eval_df[~eval_df['ID'].isin(event_ids_matching_truth)]
unexpected_events_seen = len(eval_only_events)

# QC pass
# Write results

/var/folders/79/npsx5gsd7_3c8jbl3d8h6ggc0000gp/T/ipykernel_4012/2295821188.py:84: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  truth_events_fraction_covered = truth_with_eval.groupby(['event_index']).apply(group_truth_events)

In [53]:
truth_with_eval['overlap_length'].sum()

np.float64(10928.0)

In [ ]:
truth

,event_index,contig,svtype,start,end,start_exon_idx,end_exon_idx
0,5,chr7,DEL,143132117,143184435,8401.0,8406.0
1,0,chr12,DUP,10431117,10435986,1462.0,1468.0
2,1,chr14,DEL,22450089,22512908,471.0,509.0
3,2,chr14,DEL,106470264,106627552,6431.0,6449.0
4,3,chr19,DUP,54803652,54818599,10862.0,10873.0
5,4,chr22,DEL,20355240,20356696,487.0,488.0

In [57]:
truth_with_eval.query('eval_length > overlap_length')

,index_truth,event_index,contig_truth,svtype_truth,start_truth,end_truth,start_exon_idx_truth,end_exon_idx_truth,exon_idx_truth,start_exon_truth,end_exon_truth,event_exon_start_truth,event_exon_end_truth,index_eval,contig_eval,start_eval,end_eval,ALT,svtype_eval,ID,start_exon_idx_eval,end_exon_idx_eval,exon_idx_eval,start_exon_eval,end_exon_eval,event_exon_start_eval,event_exon_end_eval,_merge,overlap_start,overlap_end,overlap_length,truth_length,eval_length
chr19_10873_DUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155,chr19,54803552,54825178,<DUP>,DUP,CNV_chr19_54803552_54825178,10862,10876,10873,54819713,54820012,54819713,54820012,right_only,NaN,NaN,0.0,NaN,299
chr19_10874_DUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155,chr19,54803552,54825178,<DUP>,DUP,CNV_chr19_54803552_54825178,10862,10876,10874,54821565,54821858,54821565,54821858,right_only,NaN,NaN,0.0,NaN,293
chr19_10875_DUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155,chr19,54803552,54825178,<DUP>,DUP,CNV_chr19_54803552_54825178,10862,10876,10875,54825028,54825078,54825028,54825078,right_only,NaN,NaN,0.0,NaN,50

In [55]:
eval_length_dedup

np.int64(11570)

## Old

In [ ]:
import pandas as pd
import numpy as np

pd.options.display.max_columns = None



def add_exon_idxs(df, exons):
    contigs = set(df.contig)
    for contig in contigs:
        df.loc[df.contig==contig,"start_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].end,
                                                                   df.loc[df.contig==contig].start,"left")
        df.loc[df.contig==contig,"end_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].start,
                                                                   df.loc[df.contig==contig].end,"right")
    return df.astype({'start_exon_idx': int, 'end_exon_idx': int})

def get_exon_expanded_events_maybe(df, exons):
    add_exon_idxs(df, exons)
    # Does this not allow single exon events?
    df = df.loc[df.start_exon_idx != df.end_exon_idx].reset_index()
    df_expanded = df.loc[df.index.repeat(df.end_exon_idx-df.start_exon_idx)]
    df_expanded['exon_idx'] = df_expanded.groupby(df_expanded.index).cumcount() + df_expanded.start_exon_idx
    
    # Add exon start and end positions
    df_expanded = df_expanded.merge(exons[['contig', 'exon_idx', 'start','end']], on=['contig', 'exon_idx'], suffixes=('', '_exon'))
    return df_expanded


def add_exon_idxs(df, exons):
        contigs = set(df.contig)
        for contig in contigs:
            df.loc[df.contig==contig,"start_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].end,
                                                                       df.loc[df.contig==contig].start,"left")
            df.loc[df.contig==contig,"end_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].start,
                                                                       df.loc[df.contig==contig].end,"right")

def get_exon_expanded_events(df, exons):
    add_exon_idxs(df, exons)
    df = df.loc[df.start_exon_idx != df.end_exon_idx].reset_index().astype({'start_exon_idx':int,'end_exon_idx':int})
    df_expanded = df.loc[df.index.repeat(df.end_exon_idx-df.start_exon_idx)]
    df_expanded['exon_idx'] = df_expanded.groupby(df_expanded.index).cumcount() + df_expanded.start_exon_idx
    df_expanded = df_expanded.set_index(df_expanded.contig + "_" + df_expanded.exon_idx.astype(str))
    df_expanded = df_expanded.join(exons[['start','end']], rsuffix='_exon')
    df_expanded['event_exon_start']=np.maximum(df_expanded.start, df_expanded.start_exon)
    df_expanded['event_exon_end']=np.minimum(df_expanded.end, df_expanded.end_exon)
    df_expanded = df_expanded.set_index(df_expanded.index + "_" + df_expanded.svtype)
    return df_expanded


def extract_end_from_info(info):
    infos = info.split(';')
    for i in infos:
        if i.startswith('END='):
            return i.replace('END=', '')    

def standardize_gt_vcf(df):
    df['end'] = df['INFO'].apply(extract_end_from_info).astype(int)
    df["svtype"] = df.ALT.str.replace("<","").str.replace(">","")
    for num,f in enumerate(df.loc[0,'FORMAT'].split(':')):
        df[f] = df['SAMPLE'].str.split(':').apply(lambda x: x[num])
    return df

def read_vcf_to_df(vcf_path, sample_name, sample_alias):
    df = pd.read_csv(vcf_path, sep='\t',comment='#',compression='gzip',
                         names=['contig','start','ID','REF','ALT','QUAL','FILTER','INFO','FORMAT','SAMPLE'])
    
    df = standardize_gt_vcf(df)
    df = df.query("ALT != '.' and FILTER=='PASS'").copy()
    df['end'] = df['INFO'].str.split(";").apply(lambda x: x[0]).str.split('=').apply(lambda x: x[1]).astype(int)
    df['sample_name']=sample_name
    df['control_sample_name']=sample_alias
    return df[['contig', 'start', 'end', 'sample_name', 'control_sample_name', 'ALT', 'svtype']]

paths = ['gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/c5a89822-b126-4f64-a769-794a2db2d4d5/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/d8f9fe2b-a079-4fae-88e9-fa6fe8d0e06b/call-FilterVCF/0437225738.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/19908fa6-c22b-40da-84c7-be6a6c151da5/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/b08b14a1-90f7-45ed-81dd-88e6f99c6e80/call-FilterVCF/0437225744.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/491aa495-33c0-41a9-a7e5-bb564dede818/CNVCallingAndMergeForFabric/c6396060-71d2-465c-84b2-0c2c2b4809c3/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/9764b4cf-af73-4095-940e-3e482abe684b/call-FilterVCF/0437225751.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/a6305bbb-6e10-4439-89e3-7cabac97a4d9/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/68b32369-7fc9-4d09-9f84-ee0eb88f1780/call-FilterVCF/0437225752.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/a0121b59-1d7f-4622-be5a-0e34a927077a/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/244d1d8e-88d1-43f3-885f-76f4ba9fc1ab/call-FilterVCF/0437225753.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/abb9ed4e-8fcd-44cb-b196-e3ae16bc166a/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/6f8e7059-cfc3-4684-b88f-27c4c864d29b/call-FilterVCF/0437225754.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/491aa495-33c0-41a9-a7e5-bb564dede818/CNVCallingAndMergeForFabric/82f0ad40-3db5-4bb3-8f28-468655d8231b/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/8289dd66-d420-4559-8161-5756121c8776/call-FilterVCF/0437225755.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/2610faa2-d735-4f13-a0ef-1ab481faa762/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/1168faac-ae1e-45b2-8c92-8d40f66e1c7f/call-FilterVCF/0437227355.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/504ce16a-0001-4f21-ba1c-effea2b92d7d/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/14c267a3-a4b8-4031-9513-14ecec6cbbc1/call-FilterVCF/0437227356.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/37a3ce6e-5d9c-4963-ae05-6f44331d8902/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/5a7c0cdf-d0da-4839-ac89-deaa02e2e288/call-FilterVCF/0437227363.filtered.genotyped-segments.vcf.gz']
sample_names = ['0437225738',
 '0437225744',
 '0437225751',
 '0437225752',
 '0437225753',
 '0437225754',
 '0437225755',
 '0437227355',
 '0437227356',
 '0437227363']
control_sample_names = ['NA12878',
 'NA12878',
 'NA24385',
 'NA24385',
 'NA24385',
 'NA24385',
 'NA24385',
 'NA12878',
 'NA12878',
 'NA12878']

intervals_path = "gs://fc-9b3068ac-c9f3-48c2-b157-5d7e7286e32f/twist_hg38_targets.interval_list"

intervals = pd.read_csv(intervals_path, sep="\t", comment="@", names = ["contig","start","end","dummy1","dummy2"])
intervals['contig_idx'] = intervals.groupby('contig').cumcount()
intervals = intervals.set_index(intervals.contig + "_" + intervals.contig_idx.astype(str))

control_events = pd.concat([read_vcf_to_df(paths[i], sample_names[i], control_sample_names[i]) for i in range(len(paths))], ignore_index=True)

control_events_expanded = get_exon_expanded_events(control_events, intervals)

control_events_expanded = control_events_expanded.rename(columns={'index': 'event_id'})

In [140]:
control_events.sort_values(by=['contig', 'start'])

,contig,start,end,sample_name,control_sample_name,ALT,svtype,start_exon_idx,end_exon_idx
6,chr12,10431017,10436086,0437225751,NA24385,<DUP>,DUP,1462.0,1468.0
11,chr12,10431017,10436086,0437225752,NA24385,<DUP>,DUP,1462.0,1468.0
19,chr12,10431017,10436086,0437225753,NA24385,<DUP>,DUP,1462.0,1468.0
26,chr12,10431017,10436086,0437225754,NA24385,<DUP>,DUP,1462.0,1468.0
33,chr12,10431017,10436086,0437225755,NA24385,<DUP>,DUP,1462.0,1468.0
12,chr12,123973844,124013030,0437225752,NA24385,<DUP>,DUP,10800.0,10803.0
7,chr14,22449013,22513008,0437225751,NA24385,<DEL>,DEL,470.0,509.0
27,chr14,22449013,22513008,0437225754,NA24385,<DEL>,DEL,470.0,509.0
34,chr14,22449013,22513008,0437225755,NA24385,<DEL>,DEL,470.0,509.0
13,chr14,22449989,22513008,0437225752,NA24385,<DEL>,DEL,471.0,509.0
20,chr14,22449989,22513008,0437225753,NA24385,<DEL>,DEL,471.0,509.0
28,chr14,106422061,106511652,0437225754,NA24385,<DEL>,DEL,6430.0,6437.0
35,chr14,106422061,106511652,0437225755,NA24385,<DEL>,DEL,6430.0,6437.0
14,chr14,106470164,106511652,0437225752,NA24385,<DEL>,DEL,6431.0,6437.0
21,chr14,106470164,106511652,0437225753,NA24385,<DEL>,DEL,6431.0,6437.0
8,chr14,106537710,106627593,0437225751,NA24385,<DEL>,DEL,6437.0,6449.0
15,chr14,106537710,106627593,0437225752,NA24385,<DEL>,DEL,6437.0,6449.0
22,chr14,106537710,106627593,0437225753,NA24385,<DEL>,DEL,6437.0,6449.0
29,chr14,106537710,106627593,0437225754,NA24385,<DEL>,DEL,6437.0,6449.0
36,chr14,106537710,106627593,0437225755,NA24385,<DEL>,DEL,6437.0,6449.0
9,chr19,54783386,54825178,0437225751,NA24385,<DUP>,DUP,10860.0,10876.0
16,chr19,54803552,54818699,0437225752,NA24385,<DUP>,DUP,10862.0,10873.0
23,chr19,54803552,54825178,0437225753,NA24385,<DUP>,DUP,10862.0,10876.0
30,chr19,54803552,54825178,0437225754,NA24385,<DUP>,DUP,10862.0,10876.0
37,chr19,54803552,54818699,0437225755,NA24385,<DUP>,DUP,10862.0,10873.0
39,chr2,131530479,131533498,0437227355,NA12878,<DEL>,DEL,7996.0,8002.0
2,chr2,131532489,131533498,0437225744,NA12878,<DEL>,DEL,7998.0,8002.0
42,chr2,131532489,131533498,0437227356,NA12878,<DEL>,DEL,7998.0,8002.0
45,chr2,131532489,131533498,0437227363,NA12878,<DEL>,DEL,7998.0,8002.0
17,chr22,20355240,20356796,0437225752,NA24385,<DEL>,DEL,487.0,488.0
24,chr22,20355240,20356796,0437225753,NA24385,<DEL>,DEL,487.0,488.0
31,chr22,20355240,20356796,0437225754,NA24385,<DEL>,DEL,487.0,488.0
38,chr22,20355240,20356796,0437225755,NA24385,<DEL>,DEL,487.0,488.0
1,chr22,22098646,22698507,0437225738,NA12878,<DEL>,DEL,775.0,835.0
4,chr22,22098646,22595156,0437225744,NA12878,<DEL>,DEL,775.0,824.0
41,chr22,22098646,22698507,0437227355,NA12878,<DEL>,DEL,775.0,835.0
44,chr22,22098646,22713303,0437227356,NA12878,<DEL>,DEL,775.0,839.0
47,chr22,22098646,22712564,0437227363,NA12878,<DEL>,DEL,775.0,838.0
5,chr7,143132017,143184535,0437225751,NA24385,<DEL>,DEL,8401.0,8406.0
10,chr7,143132017,143184535,0437225752,NA24385,<DEL>,DEL,8401.0,8406.0
18,chr7,143132017,143184535,0437225753,NA24385,<DEL>,DEL,8401.0,8406.0
25,chr7,143132017,143184535,0437225754,NA24385,<DEL>,DEL,8401.0,8406.0
32,chr7,143132017,143184535,0437225755,NA24385,<DEL>,DEL,8401.0,8406.0
0,chr9,39073790,39150077,0437225738,NA12878,<DUP>,DUP,1957.0,1972.0
3,chr9,39073790,39361909,0437225744,NA12878,<DUP>,DUP,1957.0,1985.0
40,chr9,39073790,39361909,0437227355,NA12878,<DUP>,DUP,1957.0,1985.0
43,chr9,39073790,39361909,0437227356,NA12878,<DUP>,DUP,1957.0,1985.0
46,chr9,39073790,39361909,0437227363,NA12878,<DUP>,DUP,1957.0,1985.0

In [123]:
control_events_expanded.sort_values(by=['contig', 'start']).query('contig == "chr12" and start_exon_idx > 10000')

,event_id,contig,start,end,sample_name,control_sample_name,ALT,svtype,start_exon_idx,end_exon_idx,exon_idx,start_exon,end_exon,event_exon_start,event_exon_end
chr12_10800_DUP,12,chr12,123973844,124013030,0437225752,NA24385,<DUP>,DUP,10800,10803,10800,123973944,123974020,123973944,123974020
chr12_10801_DUP,12,chr12,123973844,124013030,0437225752,NA24385,<DUP>,DUP,10800,10803,10801,123988043,123988138,123988043,123988138
chr12_10802_DUP,12,chr12,123973844,124013030,0437225752,NA24385,<DUP>,DUP,10800,10803,10802,124012145,124012930,124012145,124012930

In [124]:
# Count the number of unique sample_names for each index
index_sample_counts = control_events_expanded.groupby(control_events_expanded.index)['sample_name'].nunique()

# Filter indices that are present in at least 4 samples
valid_indices = index_sample_counts[index_sample_counts >= 4].index

# Filter the dataframe based on valid indices
filtered_control_events_expanded = control_events_expanded.loc[valid_indices]
filtered_control_events_expanded

,event_id,contig,start,end,sample_name,control_sample_name,ALT,svtype,start_exon_idx,end_exon_idx,exon_idx,start_exon,end_exon,event_exon_start,event_exon_end
chr12_1462_DUP,6,chr12,10431017,10436086,0437225751,NA24385,<DUP>,DUP,1462,1468,1462,10431117,10431228,10431117,10431228
chr12_1462_DUP,11,chr12,10431017,10436086,0437225752,NA24385,<DUP>,DUP,1462,1468,1462,10431117,10431228,10431117,10431228
chr12_1462_DUP,19,chr12,10431017,10436086,0437225753,NA24385,<DUP>,DUP,1462,1468,1462,10431117,10431228,10431117,10431228
chr12_1462_DUP,26,chr12,10431017,10436086,0437225754,NA24385,<DUP>,DUP,1462,1468,1462,10431117,10431228,10431117,10431228
chr12_1462_DUP,33,chr12,10431017,10436086,0437225755,NA24385,<DUP>,DUP,1462,1468,1462,10431117,10431228,10431117,10431228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
chr9_1983_DUP,46,chr9,39073790,39361909,0437227363,NA12878,<DUP>,DUP,1957,1985,1983,39357758,39357818,39357758,39357818
chr9_1984_DUP,3,chr9,39073790,39361909,0437225744,NA12878,<DUP>,DUP,1957,1985,1984,39358074,39361809,39358074,39361809
chr9_1984_DUP,40,chr9,39073790,39361909,0437227355,NA12878,<DUP>,DUP,1957,1985,1984,39358074,39361809,39358074,39361809
chr9_1984_DUP,43,chr9,39073790,39361909,0437227356,NA12878,<DUP>,DUP,1957,1985,1984,39358074,39361809,39358074,39361809
chr9_1984_DUP,46,chr9,39073790,39361909,0437227363,NA12878,<DUP>,DUP,1957,1985,1984,39358074,39361809,39358074,39361809

In [125]:
filtered_control_events_expanded.query('contig == "chr22" and control_sample_name == "NA24385"')

,event_id,contig,start,end,sample_name,control_sample_name,ALT,svtype,start_exon_idx,end_exon_idx,exon_idx,start_exon,end_exon,event_exon_start,event_exon_end
chr22_487_DEL,17,chr22,20355240,20356796,0437225752,NA24385,<DEL>,DEL,487,488,487,20354340,20356696,20355240,20356696
chr22_487_DEL,24,chr22,20355240,20356796,0437225753,NA24385,<DEL>,DEL,487,488,487,20354340,20356696,20355240,20356696
chr22_487_DEL,31,chr22,20355240,20356796,0437225754,NA24385,<DEL>,DEL,487,488,487,20354340,20356696,20355240,20356696
chr22_487_DEL,38,chr22,20355240,20356796,0437225755,NA24385,<DEL>,DEL,487,488,487,20354340,20356696,20355240,20356696

In [126]:
truth = filtered_control_events_expanded.reset_index(names='event_str').groupby(['event_str', 'control_sample_name']).agg({'event_exon_start': 'max', 'event_exon_end': 'min'}).reset_index().set_index('event_str')
truth = truth.query('control_sample_name == "NA12878"')
truth

              control_sample_name  event_exon_start  event_exon_end
event_str
chr22_775_DEL             NA12878          22098746        22098806
chr22_776_DEL             NA12878          22098906        22099212
chr22_777_DEL             NA12878          22162199        22162250
chr22_778_DEL             NA12878          22162372        22162681
chr22_779_DEL             NA12878          22195799        22195844
...                           ...               ...             ...
chr9_1980_DUP             NA12878          39287980        39288064
chr9_1981_DUP             NA12878          39355689        39355919
chr9_1982_DUP             NA12878          39357132        39357189
chr9_1983_DUP             NA12878          39357758        39357818
chr9_1984_DUP             NA12878          39358074        39361809

[92 rows x 3 columns]

## Eval

In [ ]:
import pandas as pd
import numpy as np
import gzip

intervals = pd.read_csv(intervals_path, sep="\t", comment="@", names = ["contig","start","end","dummy1","dummy2"])
intervals['contig_idx'] = intervals.groupby('contig').cumcount()
intervals = intervals.set_index(intervals.contig + "_" + intervals.contig_idx.astype(str))

def add_exon_idxs(df, exons):
        contigs = set(df.contig)
        for contig in contigs:
            df.loc[df.contig==contig,"start_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].end,
                                                                       df.loc[df.contig==contig].start,"left")
            df.loc[df.contig==contig,"end_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].start,
                                                                       df.loc[df.contig==contig].end,"right")

def get_exon_expanded_events(df, exons):
    add_exon_idxs(df, exons)
    df = df.loc[df.start_exon_idx != df.end_exon_idx].reset_index().astype({'start_exon_idx':int,'end_exon_idx':int})
    df_expanded = df.loc[df.index.repeat(df.end_exon_idx-df.start_exon_idx)]
    df_expanded['exon_idx'] = df_expanded.groupby(df_expanded.index).cumcount() + df_expanded.start_exon_idx
    df_expanded = df_expanded.set_index(df_expanded.contig + "_" + df_expanded.exon_idx.astype(str))
    df_expanded = df_expanded.join(exons[['start','end']], rsuffix='_exon')
    df_expanded['event_exon_start']=np.maximum(df_expanded.start, df_expanded.start_exon)
    df_expanded['event_exon_end']=np.minimum(df_expanded.end, df_expanded.end_exon)
    df_expanded = df_expanded.set_index(df_expanded.index + "_" + df_expanded.svtype)
    return df_expanded

def extract_end_from_info(info):
    infos = info.split(';')
    for i in infos:
        if i.startswith('END='):
            return i.replace('END=', '')    

def standardize_gt_vcf(df):
    df['end'] = df['INFO'].apply(extract_end_from_info).astype(int)
    df["svtype"] = df.ALT.str.replace("<","").str.replace(">","")
    for num,f in enumerate(df.loc[0,'FORMAT'].split(':')):
        df[f] = df['SAMPLE'].str.split(':').apply(lambda x: x[num])
    return df

def get_sample_id(vcf):
    with gzip.open(vcf,"r") as f_vcf:
        for line in f_vcf:
            if line.startswith(b'#CHROM'):
                return line.split(b'\t')[-1].decode()

def read_vcf_to_df(vcf):
    df = pd.read_csv(vcf, sep='\t',comment='#',compression='gzip',
                         names=['contig','start','ID','REF','ALT','QUAL','FILTER','INFO','FORMAT','SAMPLE'])
    df = standardize_gt_vcf(df)
    df = df.query("ALT != '.' and FILTER=='PASS'").copy()
    for c in ['NP','CN','QA','QS']:
        df[c]=df[c].astype(int)
    return df

df = read_vcf_to_df(paths[0])
df_expanded = get_exon_expanded_events(df, intervals)

#vcfs = ["~{sep='","' panel_vcfs}"]
vcfs = paths
df_panel = pd.concat([read_vcf_to_df(vcf) for vcf in vcfs])
df_panel_expanded = get_exon_expanded_events(df_panel, intervals)
df_panel_expanded = truth

df_expanded_with_panel = df_expanded.join(df_panel_expanded, how="left", lsuffix="_sample", rsuffix="_panel")

df_expanded_with_panel['overlapping_panel_exon_start']=np.maximum(df_expanded_with_panel.event_exon_start_sample, df_expanded_with_panel.event_exon_start_panel)
df_expanded_with_panel['overlapping_panel_exon_end']=np.minimum(df_expanded_with_panel.event_exon_end_sample, df_expanded_with_panel.event_exon_end_panel)

df_expanded['event_exon_length']=df_expanded.event_exon_end - df_expanded.event_exon_start
df_expanded_with_panel['overlapping_panel_exon_length']=np.maximum(df_expanded_with_panel.overlapping_panel_exon_end - df_expanded_with_panel.overlapping_panel_exon_start,0).fillna(0)

df_panel_counts = df_expanded_with_panel.groupby(['ID']).agg(
    {'overlapping_panel_exon_length':'sum'}
    ).join(df_expanded.groupby('ID').agg({'event_exon_length':'sum'})
)



df_panel_counts['fraction_covered'] = df_panel_counts.overlapping_panel_exon_length/df_panel_counts.event_exon_length
#df_panel_counts = df_panel_counts.groupby(df_panel_counts.index).agg({'fraction_covered':'sum'})

sensitivity = df_panel_counts['fraction_covered'].sum()

df = df.set_index('ID').join(df_panel_counts).fillna({'PANEL_COUNT':0})

# n_panel_samples = len(set(df_panel.sample_name))
# df['PANEL_FREQ'] = df['PANEL_COUNT']/n_panel_samples



# df_panel_counts['PANEL_COUNT'] = np.where(df_panel_counts.overlapping_panel_exon_length/df_panel_counts.event_exon_length>0.8, 1, 0)
# df_panel_counts = df_panel_counts.groupby(df_panel_counts.index).agg({'PANEL_COUNT':'sum'})

# df = df.set_index('ID').join(df_panel_counts).fillna({'PANEL_COUNT':0})

# n_panel_samples = len(set(df_panel.sample_name))
# df['PANEL_FREQ'] = df['PANEL_COUNT']/n_panel_samples

# df_annotations = df[['contig','start','PANEL_FREQ','PANEL_COUNT']].copy()
# df_annotations = df_annotations.rename({"contig":"CHROM","start":"POS"}, axis=1)
# df_annotations = df_annotations.astype({"PANEL_COUNT":int})
# df_annotations.to_csv("~{basename_out}.annotations.tsv", index = False, sep="\t", float_format="%g")

## Actual production

In [115]:
import pandas as pd
import numpy as np
import gzip

intervals = pd.read_csv(intervals_path, sep="\t", comment="@", names = ["contig","start","end","dummy1","dummy2"])
intervals['contig_idx'] = intervals.groupby('contig').cumcount()
intervals = intervals.set_index(intervals.contig + "_" + intervals.contig_idx.astype(str))

def add_exon_idxs(df, exons):
        contigs = set(df.contig)
        for contig in contigs:
            df.loc[df.contig==contig,"start_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].end,
                                                                       df.loc[df.contig==contig].start,"left")
            df.loc[df.contig==contig,"end_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].start,
                                                                       df.loc[df.contig==contig].end,"right")

def get_exon_expanded_events(df, exons):
    add_exon_idxs(df, exons)
    df = df.loc[df.start_exon_idx != df.end_exon_idx].reset_index().astype({'start_exon_idx':int,'end_exon_idx':int})
    df_expanded = df.loc[df.index.repeat(df.end_exon_idx-df.start_exon_idx)]
    df_expanded['exon_idx'] = df_expanded.groupby(df_expanded.index).cumcount() + df_expanded.start_exon_idx
    df_expanded = df_expanded.set_index(df_expanded.contig + "_" + df_expanded.exon_idx.astype(str))
    df_expanded = df_expanded.join(exons[['start','end']], rsuffix='_exon')
    df_expanded['event_exon_start']=np.maximum(df_expanded.start, df_expanded.start_exon)
    df_expanded['event_exon_end']=np.minimum(df_expanded.end, df_expanded.end_exon)
    df_expanded = df_expanded.set_index(df_expanded.index + "_" + df_expanded.svtype)
    return df_expanded

def extract_end_from_info(info):
    infos = info.split(';')
    for i in infos:
        if i.startswith('END='):
            return i.replace('END=', '')    

def read_vcf_to_df(vcf):
    df = pd.read_csv(vcf, sep='\t',comment='#',compression='gzip',
                         names=['contig','start','ID','REF','ALT','QUAL','FILTER','INFO','FORMAT','SAMPLE'])
    df['end'] = df['INFO'].apply(extract_end_from_info).astype(int)
    df["svtype"] = df.ALT.str.replace("<","").str.replace(">","")
    df = df.query("ALT != '.' and FILTER=='PASS'").copy()
    return df

eval_df = read_vcf_to_df(paths[9])
eval_df_expanded = get_exon_expanded_events(eval_df, intervals)

df_panel_expanded = truth

df_expanded_with_truth = eval_df_expanded.join(df_panel_expanded, how="left", lsuffix="_sample", rsuffix="_panel")

df_expanded_with_truth['overlapping_panel_exon_start']=np.maximum(df_expanded_with_truth.event_exon_start_sample, df_expanded_with_truth.event_exon_start_panel)
df_expanded_with_truth['overlapping_panel_exon_end']=np.minimum(df_expanded_with_truth.event_exon_end_sample, df_expanded_with_truth.event_exon_end_panel)

eval_df_expanded['event_exon_length']=eval_df_expanded.event_exon_end - eval_df_expanded.event_exon_start
df_expanded_with_truth['overlapping_panel_exon_length']=np.maximum(df_expanded_with_truth.overlapping_panel_exon_end - df_expanded_with_truth.overlapping_panel_exon_start,0).fillna(0)

df_panel_counts = df_expanded_with_truth.groupby(['ID']).agg(
    {'overlapping_panel_exon_length':'sum'}
    ).join(eval_df_expanded.groupby('ID').agg({'event_exon_length':'sum'})
)

df_panel_counts['fraction_covered'] = df_panel_counts.overlapping_panel_exon_length/df_panel_counts.event_exon_length

sensitivity = df_panel_counts['fraction_covered'].sum()

df_panel_counts

,overlapping_panel_exon_length,event_exon_length,fraction_covered
ID,,,
CNV_chr22_22098646_22712564,13619.0,14007,0.9723
CNV_chr2_131532489_131533498,450.0,450,1.0000
CNV_chr9_39073790_39361909,7955.0,7955,1.0000

In [112]:
df_panel_counts

,overlapping_panel_exon_length,event_exon_length,fraction_covered
ID,,,
CNV_chr22_22098646_22698507,13619.0,13619,1.000000
CNV_chr2_131530479_131533498,450.0,836,0.538278
CNV_chr9_39073790_39361909,7955.0,7955,1.000000

In [105]:
truth

              control_sample_name  event_exon_start  event_exon_end
event_str
chr22_775_DEL             NA12878          22098746        22098806
chr22_776_DEL             NA12878          22098906        22099212
chr22_777_DEL             NA12878          22162199        22162250
chr22_778_DEL             NA12878          22162372        22162681
chr22_779_DEL             NA12878          22195799        22195844
...                           ...               ...             ...
chr9_1980_DUP             NA12878          39287980        39288064
chr9_1981_DUP             NA12878          39355689        39355919
chr9_1982_DUP             NA12878          39357132        39357189
chr9_1983_DUP             NA12878          39357758        39357818
chr9_1984_DUP             NA12878          39358074        39361809

[92 rows x 3 columns]

In [102]:
eval_df_expanded.groupby('ID').agg({'event_exon_length':'sum'})

                              event_exon_length
ID
CNV_chr22_22098646_22595156               11957
CNV_chr2_131532489_131533498                450
CNV_chr9_39073790_39361909                 7955

In [97]:
df_panel_counts

,overlapping_panel_exon_length,event_exon_length,fraction_covered
ID,,,
CNV_chr22_22098646_22595156,11957,11957,1.0
CNV_chr2_131532489_131533498,450,450,1.0
CNV_chr9_39073790_39361909,7955,7955,1.0

### original code that works

In [ ]:
import pandas as pd
import numpy as np
import gzip

intervals = pd.read_csv(intervals_path, sep="\t", comment="@", names = ["contig","start","end","dummy1","dummy2"])
intervals['contig_idx'] = intervals.groupby('contig').cumcount()
intervals = intervals.set_index(intervals.contig + "_" + intervals.contig_idx.astype(str))

def add_exon_idxs(df, exons):
        contigs = set(df.contig)
        for contig in contigs:
            df.loc[df.contig==contig,"start_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].end,
                                                                       df.loc[df.contig==contig].start,"left")
            df.loc[df.contig==contig,"end_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].start,
                                                                       df.loc[df.contig==contig].end,"right")

def get_exon_expanded_events(df, exons):
    add_exon_idxs(df, exons)
    df = df.loc[df.start_exon_idx != df.end_exon_idx].reset_index().astype({'start_exon_idx':int,'end_exon_idx':int})
    df_expanded = df.loc[df.index.repeat(df.end_exon_idx-df.start_exon_idx)]
    df_expanded['exon_idx'] = df_expanded.groupby(df_expanded.index).cumcount() + df_expanded.start_exon_idx
    df_expanded = df_expanded.set_index(df_expanded.contig + "_" + df_expanded.exon_idx.astype(str))
    df_expanded = df_expanded.join(exons[['start','end']], rsuffix='_exon')
    df_expanded['event_exon_start']=np.maximum(df_expanded.start, df_expanded.start_exon)
    df_expanded['event_exon_end']=np.minimum(df_expanded.end, df_expanded.end_exon)
    df_expanded = df_expanded.set_index(df_expanded.index + "_" + df_expanded.svtype)
    return df_expanded

def extract_end_from_info(info):
    infos = info.split(';')
    for i in infos:
        if i.startswith('END='):
            return i.replace('END=', '')    

def standardize_gt_vcf(df):
    df['end'] = df['INFO'].apply(extract_end_from_info).astype(int)
    df["svtype"] = df.ALT.str.replace("<","").str.replace(">","")
    for num,f in enumerate(df.loc[0,'FORMAT'].split(':')):
        df[f] = df['SAMPLE'].str.split(':').apply(lambda x: x[num])
    return df

def get_sample_id(vcf):
    with gzip.open(vcf,"r") as f_vcf:
        for line in f_vcf:
            if line.startswith(b'#CHROM'):
                return line.split(b'\t')[-1].decode()

def read_vcf_to_df(vcf, sample_name):
    df = pd.read_csv(vcf, sep='\t',comment='#',compression='gzip',
                         names=['contig','start','ID','REF','ALT','QUAL','FILTER','INFO','FORMAT','SAMPLE'])
    df = standardize_gt_vcf(df)
    df = df.query("ALT != '.' and FILTER=='PASS'").copy()
    for c in ['NP','CN','QA','QS']:
        df[c]=df[c].astype(int)
    df['sample_name']=sample_name
    return df

df = read_vcf_to_df(paths[0], sample_names[0])
df_expanded = get_exon_expanded_events(df, intervals)

#vcfs = ["~{sep='","' panel_vcfs}"]
vcfs = paths
df_panel = pd.concat([read_vcf_to_df(vcfs[i], sample_names[i]) for i in range(len(vcfs))])
df_panel_expanded = get_exon_expanded_events(df_panel, intervals)
#df_panel_expanded = truth
df_expanded_with_panel = df_expanded.join(df_panel_expanded, how="left", lsuffix="_sample", rsuffix="_panel")

df_expanded_with_panel['overlapping_panel_exon_start']=np.maximum(df_expanded_with_panel.event_exon_start_sample, df_expanded_with_panel.event_exon_start_panel)
df_expanded_with_panel['overlapping_panel_exon_end']=np.minimum(df_expanded_with_panel.event_exon_end_sample, df_expanded_with_panel.event_exon_end_panel)

df_expanded['event_exon_length']=df_expanded.event_exon_end - df_expanded.event_exon_start
df_expanded_with_panel['overlapping_panel_exon_length']=np.maximum(df_expanded_with_panel.overlapping_panel_exon_end - df_expanded_with_panel.overlapping_panel_exon_start,0).fillna(0)

df_panel_counts = df_expanded_with_panel.groupby(['ID_sample','sample_name_panel']).agg(
    {'overlapping_panel_exon_length':'sum'}
    ).reset_index('sample_name_panel').join(df_expanded.groupby('ID').agg({'event_exon_length':'sum'})
)

df_panel_counts['PANEL_COUNT'] = np.where(df_panel_counts.overlapping_panel_exon_length/df_panel_counts.event_exon_length>0.8, 1, 0)
df_panel_counts = df_panel_counts.groupby(df_panel_counts.index).agg({'PANEL_COUNT':'sum'})

df = df.set_index('ID').join(df_panel_counts).fillna({'PANEL_COUNT':0})

n_panel_samples = len(set(df_panel.sample_name))
df['PANEL_FREQ'] = df['PANEL_COUNT']/n_panel_samples

df_annotations = df[['contig','start','PANEL_FREQ','PANEL_COUNT']].copy()
df_annotations = df_annotations.rename({"contig":"CHROM","start":"POS"}, axis=1)
df_annotations = df_annotations.astype({"PANEL_COUNT":int})
#df_annotations.to_csv("~{basename_out}.annotations.tsv", index = False, sep="\t", float_format="%g")

In [82]:
df

,contig,start,REF,ALT,QUAL,FILTER,INFO,FORMAT,SAMPLE,end,...,NP,QA,QS,QSE,QSS,sample_name,start_exon_idx,end_exon_idx,PANEL_COUNT,PANEL_FREQ
ID,,,,,,,,,,,,,,,,,,,,,
CNV_chr9_39073790_39150077,chr9,39073790,N,<DUP>,218.74,PASS,END=39150077;PANEL_FREQ=0;PANEL_COUNT=0,GT:CN:NP:QA:QS:QSE:QSS,./.:3:15:21:219:10:23,39150077,...,15,21,219,10,23,0437225738,1957.0,1972.0,5,0.5
CNV_chr22_22098646_22698507,chr22,22098646,N,<DEL>,2199.99,PASS,END=22698507;PANEL_FREQ=0;PANEL_COUNT=0,GT:CN:NP:QA:QS:QSE:QSS,0/1:1:60:12:2200:43:66,22698507,...,60,12,2200,43,66,0437225738,775.0,835.0,5,0.5

In [73]:
df_panel_expanded.columns

Index(['index', 'contig', 'start', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER',
       'INFO', 'FORMAT', 'SAMPLE', 'end', 'svtype', 'GT', 'CN', 'NP', 'QA',
       'QS', 'QSE', 'QSS', 'start_exon_idx', 'end_exon_idx', 'exon_idx',
       'start_exon', 'end_exon', 'event_exon_start', 'event_exon_end'],
      dtype='object')

In [ ]:


df_panel_counts['fraction_covered'] = df_panel_counts.overlapping_panel_exon_length/df_panel_counts.event_exon_length
df_panel_counts = df_panel_counts.groupby(df_panel_counts.index).agg({'fraction_covered':'sum'})

df = df.set_index('ID').join(df_panel_counts).fillna({'PANEL_COUNT':0})

n_panel_samples = len(set(df_panel.sample_name))
df['PANEL_FREQ'] = df['PANEL_COUNT']/n_panel_samples

In [ ]:
import pandas as pd
import numpy as np
import gzip

intervals = pd.read_csv(intervals_path, sep="\t", comment="@", names = ["contig","start","end","dummy1","dummy2"])
intervals['contig_idx'] = intervals.groupby('contig').cumcount()
intervals = intervals.set_index(intervals.contig + "_" + intervals.contig_idx.astype(str))

def add_exon_idxs(df, exons):
        contigs = set(df.contig)
        for contig in contigs:
            df.loc[df.contig==contig,"start_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].end,
                                                                       df.loc[df.contig==contig].start,"left")
            df.loc[df.contig==contig,"end_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].start,
                                                                       df.loc[df.contig==contig].end,"right")

def get_exon_expanded_events(df, exons):
    add_exon_idxs(df, exons)
    df = df.loc[df.start_exon_idx != df.end_exon_idx].reset_index().astype({'start_exon_idx':int,'end_exon_idx':int})
    df_expanded = df.loc[df.index.repeat(df.end_exon_idx-df.start_exon_idx)]
    df_expanded['exon_idx'] = df_expanded.groupby(df_expanded.index).cumcount() + df_expanded.start_exon_idx
    df_expanded = df_expanded.set_index(df_expanded.contig + "_" + df_expanded.exon_idx.astype(str))
    df_expanded = df_expanded.join(exons[['start','end']], rsuffix='_exon')
    df_expanded['event_exon_start']=np.maximum(df_expanded.start, df_expanded.start_exon)
    df_expanded['event_exon_end']=np.minimum(df_expanded.end, df_expanded.end_exon)
    df_expanded = df_expanded.set_index(df_expanded.index + "_" + df_expanded.svtype)
    return df_expanded

def extract_end_from_info(info):
    infos = info.split(';')
    for i in infos:
        if i.startswith('END='):
            return i.replace('END=', '')    

def standardize_gt_vcf(df):
    df['end'] = df['INFO'].apply(extract_end_from_info).astype(int)
    df["svtype"] = df.ALT.str.replace("<","").str.replace(">","")
    for num,f in enumerate(df.loc[0,'FORMAT'].split(':')):
        df[f] = df['SAMPLE'].str.split(':').apply(lambda x: x[num])
    return df

def get_sample_id(vcf):
    with gzip.open(vcf,"r") as f_vcf:
        for line in f_vcf:
            if line.startswith(b'#CHROM'):
                return line.split(b'\t')[-1].decode()

def read_vcf_to_df(vcf):
    df = pd.read_csv(vcf, sep='\t',comment='#',compression='gzip',
                         names=['contig','start','ID','REF','ALT','QUAL','FILTER','INFO','FORMAT','SAMPLE'])
    df = standardize_gt_vcf(df)
    df = df.query("ALT != '.' and FILTER=='PASS'").copy()
    for c in ['NP','CN','QA','QS']:
        df[c]=df[c].astype(int)
    return df

df = read_vcf_to_df(paths[0])
df_expanded = get_exon_expanded_events(df, intervals)

#vcfs = ["~{sep='","' panel_vcfs}"]
vcfs = paths
df_panel = pd.concat([read_vcf_to_df(vcf) for vcf in vcfs])
df_panel_expanded = get_exon_expanded_events(df_panel, intervals)
#df_panel_expanded = truth

df_expanded_with_panel = df_expanded.join(df_panel_expanded, how="left", lsuffix="_sample", rsuffix="_panel")

df_expanded_with_panel['overlapping_panel_exon_start']=np.maximum(df_expanded_with_panel.event_exon_start_sample, df_expanded_with_panel.event_exon_start_panel)
df_expanded_with_panel['overlapping_panel_exon_end']=np.minimum(df_expanded_with_panel.event_exon_end_sample, df_expanded_with_panel.event_exon_end_panel)

df_expanded['event_exon_length']=df_expanded.event_exon_end - df_expanded.event_exon_start
df_expanded_with_panel['overlapping_panel_exon_length']=np.maximum(df_expanded_with_panel.overlapping_panel_exon_end - df_expanded_with_panel.overlapping_panel_exon_start,0).fillna(0)

df_panel_counts = df_expanded_with_panel.groupby(['ID_sample']).agg(
    {'overlapping_panel_exon_length':'sum'}
    ).join(df_expanded.groupby('ID').agg({'event_exon_length':'sum'})
)

df_panel_counts['PANEL_COUNT'] = np.where(df_panel_counts.overlapping_panel_exon_length/df_panel_counts.event_exon_length>0.8, 1, 0)
df_panel_counts = df_panel_counts.groupby(df_panel_counts.index).agg({'PANEL_COUNT':'sum'})

df = df.set_index('ID').join(df_panel_counts).fillna({'PANEL_COUNT':0})

n_panel_samples = len(set(df_panel.sample_name))
df['PANEL_FREQ'] = df['PANEL_COUNT']/n_panel_samples

df_annotations = df[['contig','start','PANEL_FREQ','PANEL_COUNT']].copy()
df_annotations = df_annotations.rename({"contig":"CHROM","start":"POS"}, axis=1)
df_annotations = df_annotations.astype({"PANEL_COUNT":int})
df_annotations.to_csv("~{basename_out}.annotations.tsv", index = False, sep="\t", float_format="%g")

## Test it

In [39]:
import pandas as pd
import numpy as np

all_paths = ['gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/c5a89822-b126-4f64-a769-794a2db2d4d5/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/d8f9fe2b-a079-4fae-88e9-fa6fe8d0e06b/call-FilterVCF/0437225738.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/19908fa6-c22b-40da-84c7-be6a6c151da5/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/b08b14a1-90f7-45ed-81dd-88e6f99c6e80/call-FilterVCF/0437225744.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/491aa495-33c0-41a9-a7e5-bb564dede818/CNVCallingAndMergeForFabric/c6396060-71d2-465c-84b2-0c2c2b4809c3/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/9764b4cf-af73-4095-940e-3e482abe684b/call-FilterVCF/0437225751.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/a6305bbb-6e10-4439-89e3-7cabac97a4d9/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/68b32369-7fc9-4d09-9f84-ee0eb88f1780/call-FilterVCF/0437225752.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/a0121b59-1d7f-4622-be5a-0e34a927077a/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/244d1d8e-88d1-43f3-885f-76f4ba9fc1ab/call-FilterVCF/0437225753.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/abb9ed4e-8fcd-44cb-b196-e3ae16bc166a/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/6f8e7059-cfc3-4684-b88f-27c4c864d29b/call-FilterVCF/0437225754.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/491aa495-33c0-41a9-a7e5-bb564dede818/CNVCallingAndMergeForFabric/82f0ad40-3db5-4bb3-8f28-468655d8231b/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/8289dd66-d420-4559-8161-5756121c8776/call-FilterVCF/0437225755.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/2610faa2-d735-4f13-a0ef-1ab481faa762/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/1168faac-ae1e-45b2-8c92-8d40f66e1c7f/call-FilterVCF/0437227355.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/504ce16a-0001-4f21-ba1c-effea2b92d7d/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/14c267a3-a4b8-4031-9513-14ecec6cbbc1/call-FilterVCF/0437227356.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/37a3ce6e-5d9c-4963-ae05-6f44331d8902/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/5a7c0cdf-d0da-4839-ac89-deaa02e2e288/call-FilterVCF/0437227363.filtered.genotyped-segments.vcf.gz']
sample_names = ['0437225738',
 '0437225744',
 '0437225751',
 '0437225752',
 '0437225753',
 '0437225754',
 '0437225755',
 '0437227355',
 '0437227356',
 '0437227363']
control_sample_names = ['NA12878',
 'NA12878',
 'NA24385',
 'NA24385',
 'NA24385',
 'NA24385',
 'NA24385',
 'NA12878',
 'NA12878',
 'NA12878']

paths_na12878 = [all_paths[i] for i in range(len(all_paths)) if control_sample_names[i] == 'NA12878']
paths_na24385 = [all_paths[i] for i in range(len(all_paths)) if control_sample_names[i] == 'NA24385']

intervals_path = "gs://fc-9b3068ac-c9f3-48c2-b157-5d7e7286e32f/twist_hg38_targets.interval_list"

def add_exon_idxs(df, exons):
        contigs = set(df.contig)
        for contig in contigs:
            df.loc[df.contig==contig,"start_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].end,
                                                                       df.loc[df.contig==contig].start,"left")
            df.loc[df.contig==contig,"end_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].start,
                                                                       df.loc[df.contig==contig].end,"right")

def get_exon_expanded_events(df, exons):
    add_exon_idxs(df, exons)
    df = df.loc[df.start_exon_idx != df.end_exon_idx].reset_index().astype({'start_exon_idx':int,'end_exon_idx':int})
    df_expanded = df.loc[df.index.repeat(df.end_exon_idx-df.start_exon_idx)]
    df_expanded['exon_idx'] = df_expanded.groupby(df_expanded.index).cumcount() + df_expanded.start_exon_idx
    df_expanded = df_expanded.set_index(df_expanded.contig + "_" + df_expanded.exon_idx.astype(str))
    df_expanded = df_expanded.join(exons[['start','end']], rsuffix='_exon')
    df_expanded['event_exon_start']=np.maximum(df_expanded.start, df_expanded.start_exon)
    df_expanded['event_exon_end']=np.minimum(df_expanded.end, df_expanded.end_exon)
    df_expanded = df_expanded.set_index(df_expanded.index + "_" + df_expanded.svtype)
    return df_expanded


def extract_end_from_info(info):
    infos = info.split(';')
    for i in infos:
        if i.startswith('END='):
            return i.replace('END=', '')    

def read_vcf_to_df(vcf_path):
    df = pd.read_csv(vcf_path, sep='\t',comment='#',compression='gzip',
                         names=['contig','start','ID','REF','ALT','QUAL','FILTER','INFO','FORMAT','SAMPLE'])
    
    df = df.query("ALT != '.' and FILTER=='PASS'").copy()
    df['end'] = df['INFO'].apply(extract_end_from_info).astype(int)
    df["svtype"] = df.ALT.str.replace("<","").str.replace(">","")
    return df[['contig', 'start', 'end', 'ALT', 'svtype', 'ID']]

def read_intervals_to_df(intervals_path):
    intervals = pd.read_csv(intervals_path, sep="\t", comment="@", names = ["contig","start","end","dummy1","dummy2"])
    intervals['contig_idx'] = intervals.groupby('contig').cumcount()
    intervals = intervals.set_index(intervals.contig + "_" + intervals.contig_idx.astype(str))
    return intervals

def generate_truth(intervals_path, paths):
    intervals = read_intervals_to_df(intervals_path)

    control_events = pd.concat([read_vcf_to_df(path) for path in paths], ignore_index=True)
    control_events_expanded = get_exon_expanded_events(control_events, intervals)
    control_events_expanded = control_events_expanded.rename(columns={'index': 'event_id'})

    index_sample_counts = control_events_expanded.groupby(control_events_expanded.index).size()
    passing_indices = index_sample_counts[index_sample_counts >= 4].index
    filtered_control_events_expanded = control_events_expanded.loc[passing_indices]

    truth = filtered_control_events_expanded.reset_index(names='event_str').groupby('event_str').agg({'event_exon_start': 'max', 'event_exon_end': 'min'}).reset_index().set_index('event_str')
    return truth

def evaluate_control(intervals_path, path, truth):
    intervals = read_intervals_to_df(intervals_path)
    eval_df = read_vcf_to_df(path)
    eval_df_expanded = get_exon_expanded_events(eval_df, intervals)

    df_panel_expanded = truth

    df_expanded_with_truth = eval_df_expanded.join(df_panel_expanded, how="left", lsuffix="_sample", rsuffix="_panel")

    df_expanded_with_truth['overlapping_panel_exon_start']=np.maximum(df_expanded_with_truth.event_exon_start_sample, df_expanded_with_truth.event_exon_start_panel)
    df_expanded_with_truth['overlapping_panel_exon_end']=np.minimum(df_expanded_with_truth.event_exon_end_sample, df_expanded_with_truth.event_exon_end_panel)

    eval_df_expanded['event_exon_length']=eval_df_expanded.event_exon_end - eval_df_expanded.event_exon_start
    df_expanded_with_truth['overlapping_panel_exon_length']=np.maximum(df_expanded_with_truth.overlapping_panel_exon_end - df_expanded_with_truth.overlapping_panel_exon_start,0).fillna(0)

    df_panel_counts = df_expanded_with_truth.groupby(['ID']).agg(
        {'overlapping_panel_exon_length':'sum'}
        ).join(eval_df_expanded.groupby('ID').agg({'event_exon_length':'sum'})
    )

    df_panel_counts['fraction_covered'] = df_panel_counts.overlapping_panel_exon_length/df_panel_counts.event_exon_length

    sensitivity = df_panel_counts['fraction_covered'].sum()
    return df_panel_counts, sensitivity

In [41]:
paths_na24385

['gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/491aa495-33c0-41a9-a7e5-bb564dede818/CNVCallingAndMergeForFabric/c6396060-71d2-465c-84b2-0c2c2b4809c3/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/9764b4cf-af73-4095-940e-3e482abe684b/call-FilterVCF/0437225751.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/a6305bbb-6e10-4439-89e3-7cabac97a4d9/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/68b32369-7fc9-4d09-9f84-ee0eb88f1780/call-FilterVCF/0437225752.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/a0121b59-1d7f-4622-be5a-0e34a927077a/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/244d1d8e-88d1-43f3-885f-76f4ba9fc1ab/call-FilterVCF/0437225753.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/b90e5c81-7db4-4abe-8408-b1d078f4d738/CNVCallingAndMergeForFabric/abb9ed4e-8fcd-44cb-b196-e3ae16bc166a/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/6f8e7059-cfc3-4684-b88f-27c4c864d29b/call-FilterVCF/0437225754.filtered.genotyped-segments.vcf.gz',
 'gs://fc-863da545-cfc0-4c3f-b016-4ebc35f924b2/submissions/491aa495-33c0-41a9-a7e5-bb564dede818/CNVCallingAndMergeForFabric/82f0ad40-3db5-4bb3-8f28-468655d8231b/call-SingleSampleGCNVAndFilterVCFs/SingleSampleGCNVAndFilterVCFs/8289dd66-d420-4559-8161-5756121c8776/call-FilterVCF/0437225755.filtered.genotyped-segments.vcf.gz']

In [155]:
truth = generate_truth(intervals_path, paths_na12878)
for i in range(len(paths_na12878)):
    df_panel_counts, sensitivity = evaluate_control(intervals_path, paths_na12878[i], truth)
    print(df_panel_counts[['fraction_covered']])

                             fraction_covered
ID
CNV_chr22_22098646_22698507               1.0
CNV_chr9_39073790_39150077                1.0
                              fraction_covered
ID
CNV_chr22_22098646_22595156                1.0
CNV_chr2_131532489_131533498               1.0
CNV_chr9_39073790_39361909                 1.0
                              fraction_covered
ID
CNV_chr22_22098646_22698507           1.000000
CNV_chr2_131530479_131533498          0.538278
CNV_chr9_39073790_39361909            1.000000
                              fraction_covered
ID
CNV_chr22_22098646_22713303           0.951646
CNV_chr2_131532489_131533498          1.000000
CNV_chr9_39073790_39361909            1.000000
                              fraction_covered
ID
CNV_chr22_22098646_22712564             0.9723
CNV_chr2_131532489_131533498            1.0000
CNV_chr9_39073790_39361909              1.0000

In [156]:
truth = generate_truth(intervals_path, paths_na24385)
for i in range(len(paths_na24385)):
    df_panel_counts, sensitivity = evaluate_control(intervals_path, paths_na24385[i], truth)
    print(df_panel_counts[['fraction_covered']])

                               fraction_covered
ID
CNV_chr12_10431017_10436086            1.000000
CNV_chr14_106537710_106627593          1.000000
CNV_chr14_22449013_22513008            0.995654
CNV_chr19_54783386_54825178            0.629314
CNV_chr7_143132017_143184535           1.000000
                               fraction_covered
ID
CNV_chr12_10431017_10436086                 1.0
CNV_chr12_123973844_124013030               0.0
CNV_chr14_106470164_106511652               1.0
CNV_chr14_106537710_106627593               1.0
CNV_chr14_22449989_22513008                 1.0
CNV_chr19_54803552_54818699                 1.0
CNV_chr22_20355240_20356796                 1.0
CNV_chr7_143132017_143184535                1.0
                               fraction_covered
ID
CNV_chr12_10431017_10436086            1.000000
CNV_chr14_106470164_106511652          1.000000
CNV_chr14_106537710_106627593          1.000000
CNV_chr14_22449989_22513008            1.000000
CNV_chr19_54803552_54825178            0.697027
CNV_chr22_20355240_20356796            1.000000
CNV_chr7_143132017_143184535           1.000000
                               fraction_covered
ID
CNV_chr12_10431017_10436086            1.000000
CNV_chr14_106422061_106511652          0.940966
CNV_chr14_106537710_106627593          1.000000
CNV_chr14_22449013_22513008            0.995654
CNV_chr19_54803552_54825178            0.697027
CNV_chr22_20355240_20356796            1.000000
CNV_chr7_143132017_143184535           1.000000
                               fraction_covered
ID
CNV_chr12_10431017_10436086            1.000000
CNV_chr14_106422061_106511652          0.940966
CNV_chr14_106537710_106627593          1.000000
CNV_chr14_22449013_22513008            0.995654
CNV_chr19_54803552_54818699            1.000000
CNV_chr22_20355240_20356796            1.000000
CNV_chr7_143132017_143184535           1.000000

In [149]:
index_sample_counts

chr22_775_DEL    5
chr22_776_DEL    5
chr22_777_DEL    5
chr22_778_DEL    5
chr22_779_DEL    5
                ..
chr9_1980_DUP    4
chr9_1981_DUP    4
chr9_1982_DUP    4
chr9_1983_DUP    4
chr9_1984_DUP    4
Length: 98, dtype: int64

In [128]:
truth_old = truth.copy()

In [150]:
truth.merge(truth_old, how='outer', left_index=True, right_index=True, suffixes=('_new', '_old'), indicator=True).query('_merge != "both"')

Empty DataFrame
Columns: [event_exon_start_new, event_exon_end_new, control_sample_name, event_exon_start_old, event_exon_end_old, _merge]
Index: []

## Start new

In [31]:
def get_exon_expanded_events(df, exons):
    add_exon_idxs(df, exons)
    df = df.loc[df.start_exon_idx != df.end_exon_idx].reset_index().astype({'start_exon_idx':int,'end_exon_idx':int})
    df_expanded = df.loc[df.index.repeat(df.end_exon_idx-df.start_exon_idx)]
    df_expanded['exon_idx'] = df_expanded.groupby(df_expanded.index).cumcount() + df_expanded.start_exon_idx
    df_expanded = df_expanded.set_index(df_expanded.contig + "_" + df_expanded.exon_idx.astype(str))
    df_expanded = df_expanded.join(exons[['start','end']], rsuffix='_exon')
    df_expanded['event_exon_start']=np.maximum(df_expanded.start, df_expanded.start_exon)
    df_expanded['event_exon_end']=np.minimum(df_expanded.end, df_expanded.end_exon)
    df_expanded = df_expanded.set_index(df_expanded.index + "_" + df_expanded.svtype)
    return df_expanded

intervals = read_intervals_to_df(intervals_path)

control_events = pd.concat([read_vcf_to_df(path) for path in paths_na24385], ignore_index=True)
control_events_expanded = get_exon_expanded_events(control_events, intervals)
control_events_expanded = control_events_expanded.rename(columns={'index': 'event_id'})

index_sample_counts = control_events_expanded.groupby(control_events_expanded.index).size()
passing_indices = index_sample_counts[index_sample_counts >= 4].index
filtered_control_events_expanded = control_events_expanded.loc[passing_indices]

filtered_grouped_control_events = filtered_control_events_expanded.groupby(['contig', 'exon_idx', 'svtype']).agg({'event_exon_start': 'max', 'event_exon_end': 'min'}).reset_index()

def group_and_aggregate_events(df):
    df = df.sort_values(by='exon_idx')
    df['group'] = (df['exon_idx'].diff().fillna(1) != 1).cumsum()

    aggregated = df.groupby('group').agg({
        'event_exon_start': 'min',
        'event_exon_end': 'max',
    }).reset_index(drop=True)

    return aggregated

aggregated_events = filtered_grouped_control_events.groupby(['contig', 'svtype'], group_keys=True) \
    .apply(group_and_aggregate_events, include_groups=False).reset_index().reset_index(names='event_index') \
    .rename(columns={'event_exon_start': 'start', 'event_exon_end': 'end'})

truth = aggregated_events

In [257]:
truth

   event_index contig svtype  level_2      start        end
0            0   chr2    DEL        0  131532589  131533398
1            1  chr22    DEL        0   22098746   22698407
2            2   chr9    DUP        0   39073890   39361809

In [5]:
path = paths_na12878[2]

intervals = read_intervals_to_df(intervals_path)
eval_df = read_vcf_to_df(path)
eval_df_expanded = get_exon_expanded_events(eval_df, intervals)

truth_expanded = get_exon_expanded_events(truth, intervals)
truth_with_eval = truth_expanded.join(eval_df_expanded, how="left", lsuffix="_truth", rsuffix="_eval")

truth_with_eval['overlap_start']=np.maximum(truth_with_eval.event_exon_start_truth, truth_with_eval.event_exon_start_eval)
truth_with_eval['overlap_end']=np.minimum(truth_with_eval.event_exon_end_truth, truth_with_eval.event_exon_end_eval)

truth_with_eval['eval_length']=np.maximum(truth_with_eval.overlap_end - truth_with_eval.overlap_start,0).fillna(0)
truth_with_eval['truth_length']=truth_with_eval.event_exon_end_truth - truth_with_eval.event_exon_start_truth

truth_with_eval_grouped_by_event = truth_with_eval.groupby(['event_index', 'contig_truth', 'start_truth', 'end_truth', 'svtype_truth']).agg({'truth_length':'sum','eval_length':'sum'})
truth_with_eval_grouped_by_event['fraction_covered'] = truth_with_eval_grouped_by_event.eval_length/truth_with_eval_grouped_by_event.truth_length
truth_with_eval_grouped_by_event

,,,,,truth_length,eval_length,fraction_covered
event_index,contig_truth,start_truth,end_truth,svtype_truth,,,
0,chr2,131532589,131533398,DEL,450,450,1.0
1,chr22,22098746,22698407,DEL,13619,13619,1.0
2,chr9,39073890,39361809,DUP,7955,7955,1.0

### also precision

In [38]:
path = paths_na12878[2]

def candidate_eval(path):
    intervals = read_intervals_to_df(intervals_path)
    eval_df = read_vcf_to_df(path)
    eval_df_expanded = get_exon_expanded_events(eval_df, intervals)

    truth_expanded = get_exon_expanded_events(truth, intervals)

    truth_with_eval = truth_expanded.merge(eval_df_expanded, how="outer", suffixes=("_truth", "_eval"), indicator=True, left_index=True, right_index=True)

    truth_with_eval['overlap_start']=np.maximum(truth_with_eval.event_exon_start_truth, truth_with_eval.event_exon_start_eval)
    truth_with_eval['overlap_end']=np.minimum(truth_with_eval.event_exon_end_truth, truth_with_eval.event_exon_end_eval)

    truth_with_eval['overlap_length']=np.maximum(truth_with_eval.overlap_end - truth_with_eval.overlap_start,0).fillna(0)
    truth_with_eval['truth_length']=truth_with_eval.event_exon_end_truth - truth_with_eval.event_exon_start_truth
    truth_with_eval['eval_length']=np.maximum(truth_with_eval.event_exon_end_eval - truth_with_eval.event_exon_start_eval,0).fillna(0)

    # Sensitivity
    sensitivity = truth_with_eval['overlap_length'].sum()/truth_with_eval['truth_length'].sum()

    # Precision
    precision = truth_with_eval['overlap_length'].sum()/truth_with_eval['eval_length'].sum()

    # Expected events seen
    truth_with_eval_grouped_by_event = truth_with_eval.groupby(['event_index', 'contig_truth', 'start_truth', 'end_truth', 'svtype_truth']).agg({'truth_length':'sum','overlap_length':'sum'})
    truth_with_eval_grouped_by_event['fraction_covered'] = truth_with_eval_grouped_by_event.overlap_length/truth_with_eval_grouped_by_event.truth_length
    expected_events_seen = truth_with_eval_grouped_by_event['fraction_covered'].sum()

    # Expected events not seen
    expected_events_not_seen = len(truth) - expected_events_seen

    # Unexpected events seen
    event_ids_matching_truth = truth_with_eval.loc[truth_with_eval['_merge'] == 'both', 'ID'].unique()
    eval_only_events = eval_df[~eval_df['ID'].isin(event_ids_matching_truth)]
    unexpected_events_seen = len(eval_only_events)

    print(f'Sensitivity: {sensitivity:.2f}, Precision: {precision:.2f}, Expected events seen: {expected_events_seen:.2f}, Expected events not seen: {expected_events_not_seen:.2f}, Unexpected events seen: {unexpected_events_seen}')

In [39]:
for path in paths_na24385:
    candidate_eval(path)

Sensitivity: 0.77, Precision: 0.91, Expected events seen: 4.66, Expected events not seen: 1.34, Unexpected events seen: 0
Sensitivity: 1.00, Precision: 0.92, Expected events seen: 6.00, Expected events not seen: 0.00, Unexpected events seen: 1
Sensitivity: 1.00, Precision: 0.94, Expected events seen: 6.00, Expected events not seen: 0.00, Unexpected events seen: 0
Sensitivity: 1.00, Precision: 0.94, Expected events seen: 6.00, Expected events not seen: 0.00, Unexpected events seen: 0
Sensitivity: 1.00, Precision: 0.99, Expected events seen: 6.00, Expected events not seen: 0.00, Unexpected events seen: 0

### test data

In [ ]:
root_path = '../'

truth_path = root_path + 'test/CNVControlEventsQC/test_data/inputs/truth.tsv'
intervals_path = root_path + 'test/CNVControlEventsQC/test_data/inputs/intervals.tsv'
path = root_path + 'test/CNVControlEventsQC/test_data/inputs/eval.vcf'



import pandas as pd
import numpy as np

def add_exon_idxs(df, exons):
        contigs = set(df.contig)
        for contig in contigs:
            df.loc[df.contig==contig,"start_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].end,
                                                                       df.loc[df.contig==contig].start,"left")
            df.loc[df.contig==contig,"end_exon_idx"]=np.searchsorted(exons.loc[exons.contig==contig].start,
                                                                       df.loc[df.contig==contig].end,"right")
def get_exon_expanded_events(df, exons):
    add_exon_idxs(df, exons)
    df = df.loc[df.start_exon_idx != df.end_exon_idx].reset_index().astype({'start_exon_idx':int,'end_exon_idx':int})
    df_expanded = df.loc[df.index.repeat(df.end_exon_idx-df.start_exon_idx)]
    df_expanded['exon_idx'] = df_expanded.groupby(df_expanded.index).cumcount() + df_expanded.start_exon_idx
    df_expanded = df_expanded.set_index(df_expanded.contig + "_" + df_expanded.exon_idx.astype(str))
    df_expanded = df_expanded.join(exons[['start','end']], rsuffix='_exon')
    df_expanded['event_exon_start']=np.maximum(df_expanded.start, df_expanded.start_exon)
    df_expanded['event_exon_end']=np.minimum(df_expanded.end, df_expanded.end_exon)
    df_expanded = df_expanded.set_index(df_expanded.index + "_" + df_expanded.svtype)
    return df_expanded

def extract_end_from_info(info):
    infos = info.split(';')
    for i in infos:
        if i.startswith('END='):
            return i.replace('END=', '')    

def read_vcf_to_df(vcf_path):
    df = pd.read_csv(vcf_path, sep='\t',comment='#',
                         names=['contig','start','ID','REF','ALT','QUAL','FILTER','INFO','FORMAT','SAMPLE'], dtype={'start': int})
    
    df = df.query("ALT != '.' and FILTER=='PASS'").copy()
    df['end'] = df['INFO'].apply(extract_end_from_info).astype(int)
    df["svtype"] = df.ALT.str.replace("<","").str.replace(">","")
    return df[['contig', 'start', 'end', 'ALT', 'svtype', 'ID']]

def read_intervals_to_df(intervals_path):
    intervals = pd.read_csv(intervals_path, sep="\t", comment="@", names = ["contig","start","end","dummy1","dummy2"], dtype={'start': int, 'end': int})
    intervals['contig_idx'] = intervals.groupby('contig').cumcount()
    intervals = intervals.set_index(intervals.contig + "_" + intervals.contig_idx.astype(str))
    return intervals

def read_truth(truth_path):
    truth = pd.read_csv(truth_path, sep="\t")
    truth = truth.reset_index(names='event_index')
    return truth

intervals = read_intervals_to_df(intervals_path)
truth = read_truth(truth_path)
eval_df = read_vcf_to_df(path)
eval_df_expanded = get_exon_expanded_events(eval_df, intervals)

truth_expanded = get_exon_expanded_events(truth, intervals)

truth_with_eval = truth_expanded.merge(eval_df_expanded, how="outer", suffixes=("_truth", "_eval"), indicator=True, left_index=True, right_index=True)

truth_with_eval['overlap_start']=np.maximum(truth_with_eval.event_exon_start_truth, truth_with_eval.event_exon_start_eval)
truth_with_eval['overlap_end']=np.minimum(truth_with_eval.event_exon_end_truth, truth_with_eval.event_exon_end_eval)

truth_with_eval['overlap_length']=np.maximum(truth_with_eval.overlap_end - truth_with_eval.overlap_start,0).fillna(0)

total_truth_length = (truth_expanded.event_exon_end - truth_expanded.event_exon_start).sum()
total_eval_length = (eval_df_expanded.event_exon_end - eval_df_expanded.event_exon_start).sum()

# Sensitivity
sensitivity = truth_with_eval['overlap_length'].sum()/total_truth_length

# Precision
precision = truth_with_eval['overlap_length'].sum()/total_eval_length

# Expected events seen
def calculate_truth_event_overlap(df):
    overlap_length = df.overlap_length.sum()
    truth_dedup = df.drop_duplicates(subset=['exon_idx_truth'])
    truth_dedup_length = (truth_dedup.event_exon_end_truth - truth_dedup.event_exon_start_truth).sum()
    return overlap_length / truth_dedup_length

truth_events_fraction_covered = truth_with_eval.groupby(['event_index']).apply(calculate_truth_event_overlap)
expected_events_seen = truth_events_fraction_covered.sum()

# Expected events not seen
expected_events_not_seen = len(truth) - expected_events_seen

# Unexpected events seen
def calculate_eval_event_overlap(df):
    overlap_length = df.overlap_length.sum()
    eval_dedup = df.drop_duplicates(subset=['exon_idx_eval'])
    eval_dedup_length = (eval_dedup.event_exon_end_eval - eval_dedup.event_exon_start_eval).sum()
    return overlap_length / eval_dedup_length

eval_events_fraction_covered = truth_with_eval.groupby(['ID']).apply(calculate_eval_event_overlap)
unexpected_events_seen = len(eval_df) - eval_events_fraction_covered.sum()

# Write results
# with open('precision.txt', 'w') as f:
#     f.write(f'Precision: {precision:.4f}\n')
# with open('sensitivity.txt', 'w') as f:
#     f.write(f'Sensitivity: {sensitivity:.4f}\n')
# with open('expected_events_seen.txt', 'w') as f:
#     f.write(f'Expected events seen: {expected_events_seen:.4f}\n')
# with open('expected_events_not_seen.txt', 'w') as f:
#     f.write(f'Expected events not seen: {expected_events_not_seen:.4f}\n')
# with open('unexpected_events_seen.txt', 'w') as f:
#     f.write(f'Unexpected events seen: {unexpected_events_seen}\n')
# eval_only_events.to_csv('unexpected_events.tsv', sep='\t', index=False)

print(f'Sensitivity: {sensitivity:.2f}, Precision: {precision:.2f}, Expected events seen: {expected_events_seen:.2f}, Expected events not seen: {expected_events_not_seen:.2f}, Unexpected events seen: {unexpected_events_seen}')

Sensitivity: 0.55, Precision: 0.71, Expected events seen: 7.25, Expected events not seen: 5.75, Unexpected events seen: 5

/var/folders/79/npsx5gsd7_3c8jbl3d8h6ggc0000gp/T/ipykernel_4012/2169944100.py:93: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  truth_events_fraction_covered = truth_with_eval.groupby(['event_index']).apply(calculate_truth_event_overlap)
/var/folders/79/npsx5gsd7_3c8jbl3d8h6ggc0000gp/T/ipykernel_4012/2169944100.py:100: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  eval_events_fraction_covered = truth_with_eval.groupby(['ID']).apply(calculate_eval_event_overlap)

In [75]:
eval_events_fraction_covered

ID
false_positive_1      0.0
full                  1.0
half_left             1.0
half_right            1.0
partial               1.0
spanning_1.5_exons    1.0
spanning_2_exons      1.0
spanning_part_exon    0.5
two_events_1          1.0
two_events_2          1.0
two_truth_events      0.4
wrong_svtype          0.0
dtype: float64

In [16]:
eval_length_dedup = truth_with_eval.drop_duplicates(subset=['ID', 'exon_idx_eval'])
eval_length_dedup.eval_length.sum()

np.float64(470.0)

In [13]:
truth_length_dedup = truth_with_eval.drop_duplicates(subset=['contig_truth', 'start_truth', 'end_truth', 'svtype_truth', 'exon_idx_truth'])
truth_length_dedup

,index_truth,event_index,contig_truth,start_truth,end_truth,svtype_truth,length,start_exon_idx_truth,end_exon_idx_truth,exon_idx_truth,start_exon_truth,end_exon_truth,event_exon_start_truth,event_exon_end_truth,index_eval,contig_eval,start_eval,end_eval,ALT,svtype_eval,ID,start_exon_idx_eval,end_exon_idx_eval,exon_idx_eval,start_exon_eval,end_exon_eval,event_exon_start_eval,event_exon_end_eval,_merge,overlap_start,overlap_end,overlap_length,truth_length,eval_length
chr1_0_DUP,0.0,0.0,chr1,100.0,150.0,DUP,50.0,0.0,1.0,0.0,100.0,150.0,100.0,150.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,NaN,NaN,0.0,50.0,0.0
chr1_1_DEL,1.0,1.0,chr1,200.0,250.0,DEL,50.0,1.0,2.0,1.0,200.0,250.0,200.0,250.0,1.0,chr1,190.0,220.0,<DEL>,DEL,half_left,1.0,2.0,1.0,200.0,250.0,200.0,220.0,both,200.0,220.0,20.0,50.0,20.0
chr1_2_DUP,2.0,2.0,chr1,300.0,350.0,DUP,50.0,2.0,3.0,2.0,300.0,350.0,300.0,350.0,2.0,chr1,290.0,360.0,<DUP>,DUP,full,2.0,3.0,2.0,300.0,350.0,300.0,350.0,both,300.0,350.0,50.0,50.0,50.0
chr1_3_DEL,3.0,3.0,chr1,400.0,450.0,DEL,50.0,3.0,4.0,3.0,400.0,450.0,400.0,450.0,3.0,chr1,410.0,440.0,<DEL>,DEL,partial,3.0,4.0,3.0,400.0,450.0,410.0,440.0,both,410.0,440.0,30.0,50.0,30.0
chr1_4_DUP,4.0,4.0,chr1,500.0,550.0,DUP,50.0,4.0,5.0,4.0,500.0,550.0,500.0,550.0,4.0,chr1,520.0,590.0,<DUP>,DUP,half_right,4.0,5.0,4.0,500.0,550.0,520.0,550.0,both,520.0,550.0,30.0,50.0,30.0
chr1_5_DUP,5.0,5.0,chr1,600.0,650.0,DUP,50.0,5.0,6.0,5.0,600.0,650.0,600.0,650.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,NaN,NaN,0.0,50.0,0.0
chr1_6_DUP,6.0,6.0,chr1,700.0,750.0,DUP,50.0,6.0,7.0,6.0,700.0,750.0,700.0,750.0,6.0,chr1,710.0,720.0,<DUP>,DUP,two_events_1,6.0,7.0,6.0,700.0,750.0,710.0,720.0,both,710.0,720.0,10.0,50.0,10.0
chr1_7_DUP,7.0,7.0,chr1,810.0,820.0,DUP,10.0,7.0,8.0,7.0,800.0,850.0,810.0,820.0,8.0,chr1,800.0,850.0,<DUP>,DUP,two_truth_events,7.0,8.0,7.0,800.0,850.0,800.0,850.0,both,810.0,820.0,10.0,10.0,50.0
chr1_7_DUP,8.0,8.0,chr1,830.0,840.0,DUP,10.0,7.0,8.0,7.0,800.0,850.0,830.0,840.0,8.0,chr1,800.0,850.0,<DUP>,DUP,two_truth_events,7.0,8.0,7.0,800.0,850.0,800.0,850.0,both,830.0,840.0,10.0,10.0,50.0
chr2_0_DEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,chr2,100.0,195.0,<DEL>,DEL,wrong_svtype,0.0,1.0,0.0,100.0,150.0,100.0,150.0,right_only,NaN,NaN,0.0,NaN,50.0
chr2_0_DUP,9.0,9.0,chr2,100.0,190.0,DUP,50.0,0.0,1.0,0.0,100.0,150.0,100.0,150.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,NaN,NaN,0.0,50.0,0.0
chr2_2_DUP,10.0,10.0,chr2,290.0,460.0,DUP,100.0,2.0,4.0,2.0,300.0,350.0,300.0,350.0,10.0,chr2,295.0,455.0,<DUP>,DUP,spanning_2_exons,2.0,4.0,2.0,300.0,350.0,300.0,350.0,both,300.0,350.0,50.0,50.0,50.0
chr2_3_DUP,10.0,10.0,chr2,290.0,460.0,DUP,100.0,2.0,4.0,3.0,400.0,450.0,400.0,450.0,10.0,chr2,295.0,455.0,<DUP>,DUP,spanning_2_exons,2.0,4.0,3.0,400.0,450.0,400.0,450.0,both,400.0,450.0,50.0,50.0,50.0
chr2_5_DUP,11.0,11.0,chr2,580.0,730.0,DUP,80.0,5.0,7.0,5.0,600.0,650.0,600.0,650.0,11.0,chr2,570.0,710.0,<DUP>,DUP,spanning_1.5_exons,5.0,7.0,5.0,600.0,650.0,600.0,650.0,both,600.0,650.0,50.0,50.0,50.0
chr2_6_DUP,11.0,11.0,chr2,580.0,730.0,DUP,80.0,5.0,7.0,6.0,700.0,750.0,700.0,730.0,11.0,chr2,570.0,710.0,<DUP>,DUP,spanning_1.5_exons,5.0,7.0,6.0,700.0,750.0,700.0,710.0,both,700.0,710.0,10.0,30.0,10.0
chr2_7_DUP,12.0,12.0,chr2,820.0,830.0,DUP,10.0,7.0,8.0,7.0,800.0,850.0,820.0,830.0,12.0,chr2,815.0,825.0,<DUP>,DUP,spanning_part_exon,7.0,8.0,7.0,800.0,850.0,815.0,825.0,both,820.0,825.0,5.0,10.0,10.0

In [10]:
truth_length_dedup.truth_length.sum()

np.float64(610.0)

In [40]:
event_ids_matching_truth

array(['CNV_chr22_22098646_22698507', 'CNV_chr2_131530479_131533498',
       'CNV_chr9_39073790_39361909'], dtype=object)

In [320]:
truth_with_eval_grouped_by_event = truth_with_eval.groupby(['contig_truth', 'start_truth', 'end_truth', 'svtype_truth']).agg({'truth_length':'sum', 'eval_length':'sum','overlap_length':'sum'})
truth_with_eval_grouped_by_event['ppv'] = truth_with_eval_grouped_by_event.overlap_length/truth_with_eval_grouped_by_event.eval_length

In [321]:
truth_with_eval_grouped_by_event

,,,,truth_length,eval_length,overlap_length,ppv
contig_truth,start_truth,end_truth,svtype_truth,,,,
chr2,131532589.0,131533398.0,DEL,450.0,450,450.0,1.0
chr22,22098746.0,22698407.0,DEL,13619.0,13619,13619.0,1.0
chr9,39073890.0,39361809.0,DUP,7955.0,7955,7955.0,1.0

In [311]:
truth_with_eval['overlap_length'].sum() / truth_with_eval['eval_length'].sum()

np.float64(0.9827755466309683)

In [312]:
truth_with_eval['overlap_length'].sum() / truth_with_eval['truth_length'].sum()

np.float64(1.0)

In [314]:
truth_with_eval.columns

Index(['event_index', 'contig_truth', 'svtype_truth', 'level_2', 'start_truth',
       'end_truth', 'start_exon_idx_truth', 'end_exon_idx_truth',
       'exon_idx_truth', 'start_exon_truth', 'end_exon_truth',
       'event_exon_start_truth', 'event_exon_end_truth', 'contig_eval',
       'start_eval', 'end_eval', 'ALT', 'svtype_eval', 'ID',
       'start_exon_idx_eval', 'end_exon_idx_eval', 'exon_idx_eval',
       'start_exon_eval', 'end_exon_eval', 'event_exon_start_eval',
       'event_exon_end_eval', '_merge', 'overlap_start', 'overlap_end',
       'overlap_length', 'truth_length', 'eval_length'],
      dtype='object')

In [317]:
truth_with_eval[['start_truth', 'end_truth', 'start_eval', 'end_eval', 'overlap_length', 'truth_length', 'eval_length']]

,start_truth,end_truth,start_eval,end_eval,overlap_length,truth_length,eval_length
chr22_775_DEL,22098746.0,22698407.0,22098646,22698507,60.0,60.0,60
chr22_776_DEL,22098746.0,22698407.0,22098646,22698507,306.0,306.0,306
chr22_777_DEL,22098746.0,22698407.0,22098646,22698507,51.0,51.0,51
chr22_778_DEL,22098746.0,22698407.0,22098646,22698507,309.0,309.0,309
chr22_779_DEL,22098746.0,22698407.0,22098646,22698507,45.0,45.0,45
...,...,...,...,...,...,...,...
chr9_1980_DUP,39073890.0,39361809.0,39073790,39361909,84.0,84.0,84
chr9_1981_DUP,39073890.0,39361809.0,39073790,39361909,230.0,230.0,230
chr9_1982_DUP,39073890.0,39361809.0,39073790,39361909,57.0,57.0,57
chr9_1983_DUP,39073890.0,39361809.0,39073790,39361909,60.0,60.0,60
chr9_1984_DUP,39073890.0,39361809.0,39073790,39361909,3735.0,3735.0,3735

In [303]:
truth_with_eval.query('_merge == "right_only"')[['ID']]

                                         ID
chr2_7996_DEL  CNV_chr2_131530479_131533498
chr2_7997_DEL  CNV_chr2_131530479_131533498

In [ ]:
# Get the IDs where _merge is 'both'
both_ids = truth_with_eval.loc[truth_with_eval['_merge'] == 'both', 'ID']

# Filter out rows where _merge is 'right_only' and ID is in both_ids
filtered_truth_with_eval = truth_with_eval[~((truth_with_eval['_merge'] == 'right_only') & (truth_with_eval['ID'].isin(both_ids)))]

filtered_truth_with_eval

In [ ]:
### What's going on here

In [ ]:
def get_exon_expanded_events(df, exons):
    add_exon_idxs(df, exons)
    df = df.loc[df.start_exon_idx != df.end_exon_idx].reset_index(drop=True).astype({'start_exon_idx':int,'end_exon_idx':int})
    df_expanded = df.loc[df.index.repeat(df.end_exon_idx-df.start_exon_idx)]
    df_expanded['exon_idx'] = df_expanded.groupby(df_expanded.index).cumcount() + df_expanded.start_exon_idx
    df_expanded = df_expanded.set_index(df_expanded.contig + "_" + df_expanded.exon_idx.astype(str))
    df_expanded = df_expanded.join(exons[['start','end']], rsuffix='_exon')
    df_expanded['event_exon_start']=np.maximum(df_expanded.start, df_expanded.start_exon)
    df_expanded['event_exon_end']=np.minimum(df_expanded.end, df_expanded.end_exon)
    df_expanded = df_expanded.set_index(df_expanded.index + "_" + df_expanded.svtype)
    return df_expanded

intervals = read_intervals_to_df(intervals_path)

control_events = pd.concat([read_vcf_to_df(path) for path in paths_na12878], ignore_index=True)
control_events_expanded = get_exon_expanded_events(control_events, intervals)

index_sample_counts = control_events_expanded.groupby(control_events_expanded.index).size()
passing_indices = index_sample_counts[index_sample_counts >= 4].index
filtered_control_events_expanded = control_events_expanded.loc[passing_indices]

filtered_grouped_control_events = filtered_control_events_expanded.groupby(['contig', 'exon_idx', 'svtype']).agg({'event_exon_start': 'max', 'event_exon_end': 'min'}).reset_index()

def group_and_aggregate_events(df):
    df = df.sort_values(by='exon_idx')
    df['group'] = (df['exon_idx'].diff().fillna(1) != 1).cumsum()

    aggregated = df.groupby('group').agg({
        'event_exon_start': 'min',
        'event_exon_end': 'max',
    }).reset_index(drop=True)

    return aggregated

aggregated_events = filtered_grouped_control_events.groupby(['contig', 'svtype'], group_keys=True) \
    .apply(group_and_aggregate_events, include_groups=False).reset_index().reset_index(names='event_index') \
    .rename(columns={'event_exon_start': 'start', 'event_exon_end': 'end'})

truth = aggregated_events

In [272]:
control_events_expanded

,contig,start,end,ALT,svtype,ID,start_exon_idx,end_exon_idx,exon_idx,start_exon,end_exon,event_exon_start,event_exon_end
chr9_1957_DUP,chr9,39073790,39150077,<DUP>,DUP,CNV_chr9_39073790_39150077,1957,1972,1957,39073890,39074011,39073890,39074011
chr9_1958_DUP,chr9,39073790,39150077,<DUP>,DUP,CNV_chr9_39073790_39150077,1957,1972,1958,39078385,39078456,39078385,39078456
chr9_1959_DUP,chr9,39073790,39150077,<DUP>,DUP,CNV_chr9_39073790_39150077,1957,1972,1959,39078690,39078920,39078690,39078920
chr9_1960_DUP,chr9,39073790,39150077,<DUP>,DUP,CNV_chr9_39073790_39150077,1957,1972,1960,39085736,39085823,39085736,39085823
chr9_1961_DUP,chr9,39073790,39150077,<DUP>,DUP,CNV_chr9_39073790_39150077,1957,1972,1961,39086686,39086849,39086686,39086849
...,...,...,...,...,...,...,...,...,...,...,...,...,...
chr22_833_DEL,chr22,22098646,22712564,<DEL>,DEL,CNV_chr22_22098646_22712564,775,838,833,22697951,22697996,22697951,22697996
chr22_834_DEL,chr22,22098646,22712564,<DEL>,DEL,CNV_chr22_22098646_22712564,775,838,834,22698114,22698407,22698114,22698407
chr22_835_DEL,chr22,22098646,22712564,<DEL>,DEL,CNV_chr22_22098646_22712564,775,838,835,22704329,22704374,22704329,22704374
chr22_836_DEL,chr22,22098646,22712564,<DEL>,DEL,CNV_chr22_22098646_22712564,775,838,836,22704524,22704822,22704524,22704822
chr22_837_DEL,chr22,22098646,22712564,<DEL>,DEL,CNV_chr22_22098646_22712564,775,838,837,22712419,22712464,22712419,22712464

In [263]:
control_events_expanded.rename(columns={'index': 'event_id'})

,event_id,contig,start,end,ALT,svtype,ID,start_exon_idx,end_exon_idx,exon_idx,start_exon,end_exon,event_exon_start,event_exon_end
chr9_1957_DUP,0,chr9,39073790,39150077,<DUP>,DUP,CNV_chr9_39073790_39150077,1957,1972,1957,39073890,39074011,39073890,39074011
chr9_1958_DUP,0,chr9,39073790,39150077,<DUP>,DUP,CNV_chr9_39073790_39150077,1957,1972,1958,39078385,39078456,39078385,39078456
chr9_1959_DUP,0,chr9,39073790,39150077,<DUP>,DUP,CNV_chr9_39073790_39150077,1957,1972,1959,39078690,39078920,39078690,39078920
chr9_1960_DUP,0,chr9,39073790,39150077,<DUP>,DUP,CNV_chr9_39073790_39150077,1957,1972,1960,39085736,39085823,39085736,39085823
chr9_1961_DUP,0,chr9,39073790,39150077,<DUP>,DUP,CNV_chr9_39073790_39150077,1957,1972,1961,39086686,39086849,39086686,39086849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
chr22_833_DEL,13,chr22,22098646,22712564,<DEL>,DEL,CNV_chr22_22098646_22712564,775,838,833,22697951,22697996,22697951,22697996
chr22_834_DEL,13,chr22,22098646,22712564,<DEL>,DEL,CNV_chr22_22098646_22712564,775,838,834,22698114,22698407,22698114,22698407
chr22_835_DEL,13,chr22,22098646,22712564,<DEL>,DEL,CNV_chr22_22098646_22712564,775,838,835,22704329,22704374,22704329,22704374
chr22_836_DEL,13,chr22,22098646,22712564,<DEL>,DEL,CNV_chr22_22098646_22712564,775,838,836,22704524,22704822,22704524,22704822
chr22_837_DEL,13,chr22,22098646,22712564,<DEL>,DEL,CNV_chr22_22098646_22712564,775,838,837,22712419,22712464,22712419,22712464

In [273]:
truth

   event_index contig svtype  level_2      start        end
0            0   chr2    DEL        0  131532589  131533398
1            1  chr22    DEL        0   22098746   22698407
2            2   chr9    DUP        0   39073890   39361809

In [274]:
truth_expanded

,index,event_index,contig,svtype,level_2,start,end,start_exon_idx,end_exon_idx,exon_idx,start_exon,end_exon,event_exon_start,event_exon_end
chr2_7998_DEL,0,0,chr2,DEL,0,131532589,131533398,7998,8002,7998,131532589,131532781,131532589,131532781
chr2_7999_DEL,0,0,chr2,DEL,0,131532589,131533398,7998,8002,7999,131532864,131532937,131532864,131532937
chr2_8000_DEL,0,0,chr2,DEL,0,131532589,131533398,7998,8002,8000,131533013,131533069,131533013,131533069
chr2_8001_DEL,0,0,chr2,DEL,0,131532589,131533398,7998,8002,8001,131533269,131533398,131533269,131533398
chr22_775_DEL,1,1,chr22,DEL,0,22098746,22698407,775,835,775,22098746,22098806,22098746,22098806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
chr9_1980_DUP,2,2,chr9,DUP,0,39073890,39361809,1957,1985,1980,39287980,39288064,39287980,39288064
chr9_1981_DUP,2,2,chr9,DUP,0,39073890,39361809,1957,1985,1981,39355689,39355919,39355689,39355919
chr9_1982_DUP,2,2,chr9,DUP,0,39073890,39361809,1957,1985,1982,39357132,39357189,39357132,39357189
chr9_1983_DUP,2,2,chr9,DUP,0,39073890,39361809,1957,1985,1983,39357758,39357818,39357758,39357818
chr9_1984_DUP,2,2,chr9,DUP,0,39073890,39361809,1957,1985,1984,39358074,39361809,39358074,39361809

In [275]:
intervals

         contig     start       end dummy1 dummy2  contig_idx
chr1_0     chr1     65565     65573      +      .           0
chr1_1     chr1     69037     70008      +      .           1
chr1_2     chr1    450740    451678      +      .           2
chr1_3     chr1    685716    686654      +      .           3
chr1_4     chr1    925942    926013      +      .           4
...         ...       ...       ...    ...    ...         ...
chrY_558   chrY  57191798  57191999      +      .         558
chrY_559   chrY  57192603  57192708      +      .         559
chrY_560   chrY  57194043  57194127      +      .         560
chrY_561   chrY  57196336  57196929      +      .         561
chrM_0     chrM         2     16567      +      .           0

[201775 rows x 6 columns]